-- The City of Cape Town's eight Development Management Districts and its 778
-- official suburbs, written by scripts/seed-cape-town.mjs from the City's open
-- data on 2026-10-05. 30 suburbs straddle two districts.
INSERT INTO `regions` (`id`, `name`) VALUES
	('blaauwberg', 'Blaauwberg'),
	('cape-flats', 'Cape Flats'),
	('helderberg', 'Helderberg'),
	('mitchells-plain-khayelitsha', 'Mitchells Plain/Khayelitsha'),
	('northern', 'Northern'),
	('southern', 'Southern'),
	('table-bay', 'Table Bay'),
	('tygerberg', 'Tygerberg');
--> statement-breakpoint
INSERT INTO `suburbs` (`id`, `name`, `search_key`, `region_id`) VALUES
	('atlantis-industrial', 'ATLANTIS INDUSTRIAL', 'atlantisindustrial', 'blaauwberg'),
	('avondale-wesfleur', 'AVONDALE - WESFLEUR', 'avondalewesfleur', 'blaauwberg'),
	('beacon-hill', 'BEACON HILL', 'beaconhill', 'blaauwberg'),
	('big-bay', 'BIG BAY', 'bigbay', 'blaauwberg'),
	('blaauwbergstrand', 'BLAAUWBERGSTRAND', 'blaauwbergstrand', 'blaauwberg'),
	('blouberg-rise', 'BLOUBERG RISE', 'bloubergrise', 'blaauwberg'),
	('blouberg-sands', 'BLOUBERG SANDS', 'bloubergsands', 'blaauwberg'),
	('bloubergrant', 'BLOUBERGRANT', 'bloubergrant', 'blaauwberg'),
	('brooklyn', 'BROOKLYN', 'brooklyn', 'blaauwberg'),
	('cape-farms-district-b', 'CAPE FARMS - DISTRICT B', 'capefarmsdistrictb', 'blaauwberg'),
	('century-city', 'CENTURY CITY', 'centurycity', 'blaauwberg'),
	('dunoon', 'DUNOON', 'dunoon', 'blaauwberg'),
	('flamingo-vlei', 'FLAMINGO VLEI', 'flamingovlei', 'blaauwberg'),
	('joe-slovo-park', 'JOE SLOVO PARK', 'joeslovopark', 'blaauwberg'),
	('killarney-gardens', 'KILLARNEY GARDENS', 'killarneygardens', 'blaauwberg'),
	('lagoon-beach', 'LAGOON BEACH', 'lagoonbeach', 'blaauwberg'),
	('mamre', 'MAMRE', 'mamre', 'blaauwberg'),
	('marconi-beam', 'MARCONI BEAM', 'marconibeam', 'blaauwberg'),
	('melkbosch-strand', 'MELKBOSCH STRAND', 'melkboschstrand', 'blaauwberg'),
	('metro', 'METRO', 'metro', 'blaauwberg'),
	('milnerton', 'MILNERTON', 'milnerton', 'blaauwberg'),
	('milnerton-ridge', 'MILNERTON RIDGE', 'milnertonridge', 'blaauwberg'),
	('montague-gardens', 'MONTAGUE GARDENS', 'montaguegardens', 'blaauwberg'),
	('parklands', 'PARKLANDS', 'parklands', 'blaauwberg'),
	('pella', 'PELLA', 'pella', 'blaauwberg'),
	('phoenix', 'PHOENIX', 'phoenix', 'blaauwberg'),
	('protea-park-wesfleur', 'PROTEA PARK - WESFLEUR', 'proteaparkwesfleur', 'blaauwberg'),
	('racing-park', 'RACING PARK', 'racingpark', 'blaauwberg'),
	('rivergate', 'RIVERGATE', 'rivergate', 'blaauwberg'),
	('robinvale', 'ROBINVALE', 'robinvale', 'blaauwberg'),
	('royal-ascot', 'ROYAL ASCOT', 'royalascot', 'blaauwberg'),
	('rugby', 'RUGBY', 'rugby', 'blaauwberg'),
	('sanddrift', 'SANDDRIFT', 'sanddrift', 'blaauwberg'),
	('sandown', 'SANDOWN', 'sandown', 'blaauwberg'),
	('saxonsea', 'SAXONSEA', 'saxonsea', 'blaauwberg'),
	('saxonwood', 'SAXONWOOD', 'saxonwood', 'blaauwberg'),
	('sherwood', 'SHERWOOD', 'sherwood', 'blaauwberg'),
	('summer-greens', 'SUMMER GREENS', 'summergreens', 'blaauwberg'),
	('sunningdale', 'SUNNINGDALE', 'sunningdale', 'blaauwberg'),
	('sunridge', 'SUNRIDGE', 'sunridge', 'blaauwberg'),
	('sunset-beach', 'SUNSET BEACH', 'sunsetbeach', 'blaauwberg'),
	('table-view', 'TABLE VIEW', 'tableview', 'blaauwberg'),
	('the-stables', 'THE STABLES', 'thestables', 'blaauwberg'),
	('tijgerhof', 'TIJGERHOF', 'tijgerhof', 'blaauwberg'),
	('wesfleur', 'WESFLEUR', 'wesfleur', 'blaauwberg'),
	('west-beach', 'WEST BEACH', 'westbeach', 'blaauwberg'),
	('west-riding', 'WEST RIDING', 'westriding', 'blaauwberg'),
	('witsand', 'WITSAND', 'witsand', 'blaauwberg'),
	('ysterplaat', 'YSTERPLAAT', 'ysterplaat', 'blaauwberg');
--> statement-breakpoint
INSERT INTO `suburbs` (`id`, `name`, `search_key`, `region_id`) VALUES
	('athlone', 'ATHLONE', 'athlone', 'cape-flats'),
	('belgravia', 'BELGRAVIA', 'belgravia', 'cape-flats'),
	('belthorn-estate', 'BELTHORN ESTATE', 'belthornestate', 'cape-flats'),
	('bridgetown', 'BRIDGETOWN', 'bridgetown', 'cape-flats'),
	('crawford', 'CRAWFORD', 'crawford', 'cape-flats'),
	('eagle-park', 'EAGLE PARK', 'eaglepark', 'cape-flats'),
	('false-bay-coastal-park', 'FALSE BAY COASTAL PARK', 'falsebaycoastalpark', 'cape-flats'),
	('gatesville', 'GATESVILLE', 'gatesville', 'cape-flats'),
	('grassy-park', 'GRASSY PARK', 'grassypark', 'cape-flats'),
	('guguletu', 'GUGULETU', 'guguletu', 'cape-flats'),
	('hanover-park', 'HANOVER PARK', 'hanoverpark', 'cape-flats'),
	('hatton', 'HATTON', 'hatton', 'cape-flats'),
	('hazendal', 'HAZENDAL', 'hazendal', 'cape-flats'),
	('heideveld', 'HEIDEVELD', 'heideveld', 'cape-flats'),
	('kewtown', 'KEWTOWN', 'kewtown', 'cape-flats'),
	('lansdowne', 'LANSDOWNE', 'lansdowne', 'cape-flats'),
	('lavender-hill', 'LAVENDER HILL', 'lavenderhill', 'cape-flats'),
	('lotus-river', 'LOTUS RIVER', 'lotusriver', 'cape-flats'),
	('manenberg', 'MANENBERG', 'manenberg', 'cape-flats'),
	('mountview', 'MOUNTVIEW', 'mountview', 'cape-flats'),
	('newfields', 'NEWFIELDS', 'newfields', 'cape-flats'),
	('nyanga', 'NYANGA', 'nyanga', 'cape-flats'),
	('ottery', 'OTTERY', 'ottery', 'cape-flats'),
	('parkwood', 'PARKWOOD', 'parkwood', 'cape-flats'),
	('peacock-close', 'PEACOCK CLOSE', 'peacockclose', 'cape-flats'),
	('pelikan-heights', 'PELIKAN HEIGHTS', 'pelikanheights', 'cape-flats'),
	('pelikan-park', 'PELIKAN PARK', 'pelikanpark', 'cape-flats'),
	('penlyn-estate', 'PENLYN ESTATE', 'penlynestate', 'cape-flats'),
	('pinati-estate', 'PINATI ESTATE', 'pinatiestate', 'cape-flats'),
	('rondebosch-east', 'RONDEBOSCH EAST', 'rondeboscheast', 'cape-flats'),
	('rylands', 'RYLANDS', 'rylands', 'cape-flats'),
	('sand-industria', 'SAND INDUSTRIA', 'sandindustria', 'cape-flats'),
	('seawinds', 'SEAWINDS', 'seawinds', 'cape-flats'),
	('silvertown', 'SILVERTOWN', 'silvertown', 'cape-flats'),
	('strandfontein', 'STRANDFONTEIN', 'strandfontein', 'cape-flats'),
	('surrey-estate', 'SURREY ESTATE', 'surreyestate', 'cape-flats'),
	('sybrand-park', 'SYBRAND PARK', 'sybrandpark', 'cape-flats'),
	('vanguard-estate', 'VANGUARD ESTATE', 'vanguardestate', 'cape-flats'),
	('vrygrond', 'VRYGROND', 'vrygrond', 'cape-flats'),
	('welcome-estate', 'WELCOME ESTATE', 'welcomeestate', 'cape-flats'),
	('wetton', 'WETTON', 'wetton', 'cape-flats'),
	('zeekoevlei', 'ZEEKOEVLEI', 'zeekoevlei', 'cape-flats');
--> statement-breakpoint
INSERT INTO `suburbs` (`id`, `name`, `search_key`, `region_id`) VALUES
	('admirals-park', 'ADMIRALS PARK', 'admiralspark', 'helderberg'),
	('anchorage-park', 'ANCHORAGE PARK', 'anchoragepark', 'helderberg'),
	('antilles-cayman-beach', 'ANTILLES/CAYMAN BEACH', 'antillescaymanbeach', 'helderberg'),
	('asanda', 'ASANDA', 'asanda', 'helderberg'),
	('asla-park', 'ASLA PARK', 'aslapark', 'helderberg'),
	('audas-estate', 'AUDAS ESTATE', 'audasestate', 'helderberg'),
	('bel-aire', 'BEL''AIRE', 'belaire', 'helderberg'),
	('bell-glen', 'BELL GLEN', 'bellglen', 'helderberg'),
	('bene-township', 'BENE TOWNSHIP', 'benetownship', 'helderberg'),
	('berbago', 'BERBAGO', 'berbago', 'helderberg'),
	('bizweni', 'BIZWENI', 'bizweni', 'helderberg'),
	('boskloof', 'BOSKLOOF', 'boskloof', 'helderberg'),
	('braeview', 'BRAEVIEW', 'braeview', 'helderberg'),
	('brandwacht', 'BRANDWACHT', 'brandwacht', 'helderberg'),
	('bridgebank', 'BRIDGEBANK', 'bridgebank', 'helderberg'),
	('bridgewater', 'BRIDGEWATER', 'bridgewater', 'helderberg'),
	('briza', 'BRIZA', 'briza', 'helderberg'),
	('broadlands', 'BROADLANDS', 'broadlands', 'helderberg'),
	('broadlands-park', 'BROADLANDS PARK', 'broadlandspark', 'helderberg'),
	('broadlands-village', 'BROADLANDS VILLAGE', 'broadlandsvillage', 'helderberg'),
	('carey-park', 'CAREY PARK', 'careypark', 'helderberg'),
	('carwick', 'CARWICK', 'carwick', 'helderberg'),
	('chris-hani-park', 'CHRIS HANI PARK', 'chrishanipark', 'helderberg'),
	('chris-nissen-park', 'CHRIS NISSEN PARK', 'chrisnissenpark', 'helderberg'),
	('croydon', 'CROYDON', 'croydon', 'helderberg'),
	('croydon-olive-estate', 'CROYDON OLIVE ESTATE', 'croydonoliveestate', 'helderberg'),
	('croydon-vineyard-estate', 'CROYDON VINEYARD ESTATE', 'croydonvineyardestate', 'helderberg'),
	('de-velde', 'DE VELDE', 'develde', 'helderberg'),
	('deaconville', 'DEACONVILLE', 'deaconville', 'helderberg'),
	('deepfreeze', 'DEEPFREEZE', 'deepfreeze', 'helderberg'),
	('dennegeur', 'DENNEGEUR', 'dennegeur', 'helderberg'),
	('die-wingerd', 'DIE WINGERD', 'diewingerd', 'helderberg'),
	('dobson', 'DOBSON', 'dobson', 'helderberg'),
	('dorhill', 'DORHILL', 'dorhill', 'helderberg'),
	('erinvale-estate', 'ERINVALE ESTATE', 'erinvaleestate', 'helderberg'),
	('fairview-golf-estate', 'FAIRVIEW GOLF ESTATE', 'fairviewgolfestate', 'helderberg'),
	('faure', 'FAURE', 'faure', 'helderberg'),
	('fernwood', 'FERNWOOD', 'fernwood', 'helderberg'),
	('firgrove', 'FIRGROVE', 'firgrove', 'helderberg'),
	('firgrove-rural', 'FIRGROVE RURAL', 'firgroverural', 'helderberg'),
	('firlands', 'FIRLANDS', 'firlands', 'helderberg'),
	('fraaigelegen', 'FRAAIGELEGEN', 'fraaigelegen', 'helderberg'),
	('gants-park', 'GANTS PARK', 'gantspark', 'helderberg'),
	('garden-village', 'GARDEN VILLAGE', 'gardenvillage', 'helderberg'),
	('george-park', 'GEORGE PARK', 'georgepark', 'helderberg'),
	('goede-hoop', 'GOEDE HOOP', 'goedehoop', 'helderberg'),
	('goedehoop', 'GOEDEHOOP', 'goedehoop', 'helderberg'),
	('golden-acre', 'GOLDEN ACRE', 'goldenacre', 'helderberg'),
	('golden-hill-ext-1', 'GOLDEN HILL EXT 1', 'goldenhillext1', 'helderberg'),
	('gordon-heights', 'GORDON HEIGHTS', 'gordonheights', 'helderberg'),
	('gordons-bay', 'GORDONS BAY', 'gordonsbay', 'helderberg'),
	('gordons-bay-ext-12', 'GORDONS BAY EXT 12', 'gordonsbayext12', 'helderberg'),
	('gordons-bay-village', 'GORDONS BAY VILLAGE', 'gordonsbayvillage', 'helderberg'),
	('gordons-strand-estate', 'GORDONS STRAND ESTATE', 'gordonsstrandestate', 'helderberg'),
	('greenways', 'GREENWAYS', 'greenways', 'helderberg'),
	('harbour-island', 'HARBOUR ISLAND', 'harbourisland', 'helderberg'),
	('heartland-beach-road-precinct', 'HEARTLAND BEACH ROAD PRECINCT', 'heartlandbeachroadprecinct', 'helderberg'),
	('heartland-historic-precinct', 'HEARTLAND HISTORIC PRECINCT', 'heartlandhistoricprecinct', 'helderberg'),
	('helderberg-estate', 'HELDERBERG ESTATE', 'helderbergestate', 'helderberg'),
	('helderberg-industrial-park', 'HELDERBERG INDUSTRIAL PARK', 'helderbergindustrialpark', 'helderberg'),
	('helderberg-park', 'HELDERBERG PARK', 'helderbergpark', 'helderberg'),
	('helderberg-rural', 'HELDERBERG RURAL', 'helderbergrural', 'helderberg'),
	('helderberg-village', 'HELDERBERG VILLAGE', 'helderbergvillage', 'helderberg'),
	('helderrant', 'HELDERRANT', 'helderrant', 'helderberg'),
	('heldervue', 'HELDERVUE', 'heldervue', 'helderberg'),
	('helderzicht', 'HELDERZICHT', 'helderzicht', 'helderberg'),
	('helena-heights', 'HELENA HEIGHTS', 'helenaheights', 'helderberg'),
	('heritage-park', 'HERITAGE PARK', 'heritagepark', 'helderberg'),
	('high-riding', 'HIGH RIDING', 'highriding', 'helderberg'),
	('highveld', 'HIGHVELD', 'highveld', 'helderberg'),
	('humanshof', 'HUMANSHOF', 'humanshof', 'helderberg'),
	('illaire', 'ILLAIRE', 'illaire', 'helderberg'),
	('jacques-hill', 'JACQUES HILL', 'jacqueshill', 'helderberg'),
	('jonkers-hoogte', 'JONKERS HOOGTE', 'jonkershoogte', 'helderberg'),
	('kalamunda', 'KALAMUNDA', 'kalamunda', 'helderberg'),
	('kelderhof', 'KELDERHOF', 'kelderhof', 'helderberg'),
	('la-concorde', 'LA CONCORDE', 'laconcorde', 'helderberg'),
	('la-montagne', 'LA MONTAGNE', 'lamontagne', 'helderberg'),
	('la-sandra', 'LA SANDRA', 'lasandra', 'helderberg'),
	('land-en-zeezicht', 'LAND EN ZEEZICHT', 'landenzeezicht', 'helderberg'),
	('longdown-estate', 'LONGDOWN ESTATE', 'longdownestate', 'helderberg'),
	('lourensia-park', 'LOURENSIA PARK', 'lourensiapark', 'helderberg'),
	('lwandle', 'LWANDLE', 'lwandle', 'helderberg'),
	('lynn-s-view', 'LYNN''S VIEW', 'lynnsview', 'helderberg'),
	('macassar', 'MACASSAR', 'macassar', 'helderberg'),
	('macassar-beach', 'MACASSAR BEACH', 'macassarbeach', 'helderberg'),
	('macassar-village', 'MACASSAR VILLAGE', 'macassarvillage', 'helderberg'),
	('mall-interchange', 'MALL INTERCHANGE', 'mallinterchange', 'helderberg'),
	('mall-motor-city', 'MALL MOTOR CITY', 'mallmotorcity', 'helderberg'),
	('mall-triangle', 'MALL TRIANGLE', 'malltriangle', 'helderberg'),
	('mansfield-industria', 'MANSFIELD INDUSTRIA', 'mansfieldindustria', 'helderberg'),
	('martinville', 'MARTINVILLE', 'martinville', 'helderberg'),
	('marvinpark', 'MARVINPARK', 'marvinpark', 'helderberg'),
	('mission-grounds', 'MISSION GROUNDS', 'missiongrounds', 'helderberg'),
	('montchere', 'MONTCHERE', 'montchere', 'helderberg'),
	('monte-sereno', 'MONTE SERENO', 'montesereno', 'helderberg'),
	('morningside', 'MORNINGSIDE', 'morningside', 'helderberg'),
	('mountainside', 'MOUNTAINSIDE', 'mountainside', 'helderberg'),
	('mountainside-estate', 'MOUNTAINSIDE ESTATE', 'mountainsideestate', 'helderberg'),
	('mountainside-ext-2', 'MOUNTAINSIDE EXT 2', 'mountainsideext2', 'helderberg'),
	('nature-s-valley', 'NATURE''S VALLEY', 'naturesvalley', 'helderberg'),
	('new-macassar', 'NEW MACASSAR', 'newmacassar', 'helderberg'),
	('new-scheme', 'NEW SCHEME', 'newscheme', 'helderberg'),
	('nomzamo', 'NOMZAMO', 'nomzamo', 'helderberg'),
	('nutwood', 'NUTWOOD', 'nutwood', 'helderberg'),
	('olive-grove', 'OLIVE GROVE', 'olivegrove', 'helderberg'),
	('onverwacht-gordon-s-bay', 'ONVERWACHT - GORDON''S BAY', 'onverwachtgordonsbay', 'helderberg'),
	('onverwacht-the-strand', 'ONVERWACHT - THE STRAND', 'onverwachtthestrand', 'helderberg'),
	('onverwacht-village', 'ONVERWACHT VILLAGE', 'onverwachtvillage', 'helderberg'),
	('paarde-vlei', 'PAARDE VLEI', 'paardevlei', 'helderberg'),
	('parel-vallei', 'PAREL VALLEI', 'parelvallei', 'helderberg'),
	('parelvallei-kleinhoewes', 'PARELVALLEI KLEINHOEWES', 'parelvalleikleinhoewes', 'helderberg'),
	('pearl-marina', 'PEARL MARINA', 'pearlmarina', 'helderberg'),
	('pearl-rise', 'PEARL RISE', 'pearlrise', 'helderberg'),
	('protea-park-gordon-s-bay', 'PROTEA PARK - GORDON''S BAY', 'proteaparkgordonsbay', 'helderberg'),
	('riverside', 'RIVERSIDE', 'riverside', 'helderberg'),
	('rome-glen', 'ROME GLEN', 'romeglen', 'helderberg'),
	('roundhay', 'ROUNDHAY', 'roundhay', 'helderberg'),
	('sandvlei', 'SANDVLEI', 'sandvlei', 'helderberg'),
	('schonenberg', 'SCHONENBERG', 'schonenberg', 'helderberg'),
	('sea-breeze-park', 'SEA BREEZE PARK', 'seabreezepark', 'helderberg'),
	('sercor-park', 'SERCOR PARK', 'sercorpark', 'helderberg'),
	('silvertas', 'SILVERTAS', 'silvertas', 'helderberg'),
	('silwerboomkloof', 'SILWERBOOMKLOOF', 'silwerboomkloof', 'helderberg'),
	('sir-lowry-s-pass', 'SIR LOWRY''S PASS', 'sirlowryspass', 'helderberg'),
	('sir-lowry-s-pass-village-centre', 'SIR LOWRY''S PASS VILLAGE CENTRE', 'sirlowryspassvillagecentre', 'helderberg'),
	('sitari-country-estate', 'SITARI COUNTRY ESTATE', 'sitaricountryestate', 'helderberg'),
	('smartie-town', 'SMARTIE TOWN', 'smartietown', 'helderberg'),
	('somerset-forest', 'SOMERSET FOREST', 'somersetforest', 'helderberg'),
	('somerset-ridge', 'SOMERSET RIDGE', 'somersetridge', 'helderberg'),
	('somerset-west', 'SOMERSET WEST', 'somersetwest', 'helderberg'),
	('somerset-west-business-park', 'SOMERSET WEST BUSINESS PARK', 'somersetwestbusinesspark', 'helderberg'),
	('somerset-west-country-club', 'SOMERSET WEST COUNTRY CLUB', 'somersetwestcountryclub', 'helderberg'),
	('somerset-west-nature-reserve', 'SOMERSET WEST NATURE RESERVE', 'somersetwestnaturereserve', 'helderberg'),
	('southfork', 'SOUTHFORK', 'southfork', 'helderberg'),
	('spanish-farm', 'SPANISH FARM', 'spanishfarm', 'helderberg'),
	('steenbras-view', 'STEENBRAS VIEW', 'steenbrasview', 'helderberg'),
	('stellenbosch-farms', 'STELLENBOSCH FARMS', 'stellenboschfarms', 'helderberg'),
	('strand', 'STRAND', 'strand', 'helderberg'),
	('strand-golf-club', 'STRAND GOLF CLUB', 'strandgolfclub', 'helderberg'),
	('strand-industria', 'STRAND INDUSTRIA', 'strandindustria', 'helderberg'),
	('strandvale', 'STRANDVALE', 'strandvale', 'helderberg'),
	('stuart-s-hill', 'STUART''S HILL', 'stuartshill', 'helderberg'),
	('sun-city', 'SUN CITY', 'suncity', 'helderberg'),
	('temperance-town', 'TEMPERANCE TOWN', 'temperancetown', 'helderberg'),
	('the-link', 'THE LINK', 'thelink', 'helderberg'),
	('tre-donne', 'TRE DONNE', 'tredonne', 'helderberg'),
	('twin-palms', 'TWIN PALMS', 'twinpalms', 'helderberg'),
	('van-der-stel', 'VAN DER STEL', 'vanderstel', 'helderberg'),
	('victoria-park', 'VICTORIA PARK', 'victoriapark', 'helderberg'),
	('vredenberg-somerset-west', 'VREDENBERG - SOMERSET WEST', 'vredenbergsomersetwest', 'helderberg'),
	('vredenzicht', 'VREDENZICHT', 'vredenzicht', 'helderberg'),
	('wedderwill-estate', 'WEDDERWILL ESTATE', 'wedderwillestate', 'helderberg'),
	('westridge-somerset-west', 'WESTRIDGE - SOMERSET WEST', 'westridgesomersetwest', 'helderberg'),
	('winslow', 'WINSLOW', 'winslow', 'helderberg'),
	('world-s-view-caledon-farms', 'WORLD''S VIEW - CALEDON FARMS', 'worldsviewcaledonfarms', 'helderberg'),
	('world-s-view-somerset-west', 'WORLD''S VIEW - SOMERSET WEST', 'worldsviewsomersetwest', 'helderberg');
--> statement-breakpoint
INSERT INTO `suburbs` (`id`, `name`, `search_key`, `region_id`) VALUES
	('aan-de-wijnlanden-estate', 'AAN DE WIJNLANDEN ESTATE', 'aandewijnlandenestate', 'mitchells-plain-khayelitsha'),
	('airport', 'AIRPORT', 'airport', 'mitchells-plain-khayelitsha'),
	('austinville', 'AUSTINVILLE', 'austinville', 'mitchells-plain-khayelitsha'),
	('barnet-molokwana-corner', 'BARNET MOLOKWANA CORNER', 'barnetmolokwanacorner', 'mitchells-plain-khayelitsha'),
	('beacon-valley', 'BEACON VALLEY', 'beaconvalley', 'mitchells-plain-khayelitsha'),
	('blackheath-industria', 'BLACKHEATH INDUSTRIA', 'blackheathindustria', 'mitchells-plain-khayelitsha'),
	('blue-downs-cbd', 'BLUE DOWNS CBD', 'bluedownscbd', 'mitchells-plain-khayelitsha'),
	('bongani', 'BONGANI', 'bongani', 'mitchells-plain-khayelitsha'),
	('brentwood-park-blue-downs', 'BRENTWOOD PARK - BLUE DOWNS', 'brentwoodparkbluedowns', 'mitchells-plain-khayelitsha'),
	('camelot', 'CAMELOT', 'camelot', 'mitchells-plain-khayelitsha'),
	('colorado-park', 'COLORADO PARK', 'coloradopark', 'mitchells-plain-khayelitsha'),
	('crossroads', 'CROSSROADS', 'crossroads', 'mitchells-plain-khayelitsha'),
	('de-wijnlanden-estate', 'DE WIJNLANDEN ESTATE', 'dewijnlandenestate', 'mitchells-plain-khayelitsha'),
	('delro-village', 'DELRO VILLAGE', 'delrovillage', 'mitchells-plain-khayelitsha'),
	('dennemere', 'DENNEMERE', 'dennemere', 'mitchells-plain-khayelitsha'),
	('dreamworld', 'DREAMWORLD', 'dreamworld', 'mitchells-plain-khayelitsha'),
	('driftsands', 'DRIFTSANDS', 'driftsands', 'mitchells-plain-khayelitsha'),
	('eastridge', 'EASTRIDGE', 'eastridge', 'mitchells-plain-khayelitsha'),
	('eersterivier', 'EERSTERIVIER', 'eersterivier', 'mitchells-plain-khayelitsha'),
	('eersterivier-industria', 'EERSTERIVIER INDUSTRIA', 'eersterivierindustria', 'mitchells-plain-khayelitsha'),
	('eersterivier-south', 'EERSTERIVIER SOUTH', 'eersteriviersouth', 'mitchells-plain-khayelitsha'),
	('ekuphumleni', 'EKUPHUMLENI', 'ekuphumleni', 'mitchells-plain-khayelitsha'),
	('electric-city', 'ELECTRIC CITY', 'electriccity', 'mitchells-plain-khayelitsha'),
	('endlovini', 'ENDLOVINI', 'endlovini', 'mitchells-plain-khayelitsha'),
	('enkanini', 'ENKANINI', 'enkanini', 'mitchells-plain-khayelitsha'),
	('eyethu', 'EYETHU', 'eyethu', 'mitchells-plain-khayelitsha'),
	('fairdale', 'FAIRDALE', 'fairdale', 'mitchells-plain-khayelitsha'),
	('forest-heights', 'FOREST HEIGHTS', 'forestheights', 'mitchells-plain-khayelitsha'),
	('forest-village', 'FOREST VILLAGE', 'forestvillage', 'mitchells-plain-khayelitsha'),
	('fountain-village', 'FOUNTAIN VILLAGE', 'fountainvillage', 'mitchells-plain-khayelitsha'),
	('gaylee', 'GAYLEE', 'gaylee', 'mitchells-plain-khayelitsha'),
	('good-hope', 'GOOD HOPE', 'goodhope', 'mitchells-plain-khayelitsha'),
	('graceland', 'GRACELAND', 'graceland', 'mitchells-plain-khayelitsha'),
	('greenfields', 'GREENFIELDS', 'greenfields', 'mitchells-plain-khayelitsha'),
	('hagley', 'HAGLEY', 'hagley', 'mitchells-plain-khayelitsha'),
	('happy-valley', 'HAPPY VALLEY', 'happyvalley', 'mitchells-plain-khayelitsha'),
	('harare', 'HARARE', 'harare', 'mitchells-plain-khayelitsha'),
	('harmony-village', 'HARMONY VILLAGE', 'harmonyvillage', 'mitchells-plain-khayelitsha'),
	('highgate', 'HIGHGATE', 'highgate', 'mitchells-plain-khayelitsha'),
	('highlands-village', 'HIGHLANDS VILLAGE', 'highlandsvillage', 'mitchells-plain-khayelitsha'),
	('hillcrest-heights', 'HILLCREST HEIGHTS', 'hillcrestheights', 'mitchells-plain-khayelitsha'),
	('hindle-park', 'HINDLE PARK', 'hindlepark', 'mitchells-plain-khayelitsha'),
	('hyde-park', 'HYDE PARK', 'hydepark', 'mitchells-plain-khayelitsha'),
	('ilitha-park', 'ILITHA PARK', 'ilithapark', 'mitchells-plain-khayelitsha'),
	('jacobsdal-smallholdings', 'JACOBSDAL SMALLHOLDINGS', 'jacobsdalsmallholdings', 'mitchells-plain-khayelitsha'),
	('khaya', 'KHAYA', 'khaya', 'mitchells-plain-khayelitsha'),
	('khayelitsha', 'KHAYELITSHA', 'khayelitsha', 'mitchells-plain-khayelitsha'),
	('kleinvlei-town', 'KLEINVLEI TOWN', 'kleinvleitown', 'mitchells-plain-khayelitsha'),
	('kuyasa', 'KUYASA', 'kuyasa', 'mitchells-plain-khayelitsha'),
	('lentegeur', 'LENTEGEUR', 'lentegeur', 'mitchells-plain-khayelitsha'),
	('malibu-village', 'MALIBU VILLAGE', 'malibuvillage', 'mitchells-plain-khayelitsha'),
	('mandalay', 'MANDALAY', 'mandalay', 'mitchells-plain-khayelitsha'),
	('mandela-park', 'MANDELA PARK', 'mandelapark', 'mitchells-plain-khayelitsha'),
	('mfuleni', 'MFULENI', 'mfuleni', 'mitchells-plain-khayelitsha'),
	('mitchells-plain-cbd', 'MITCHELLS PLAIN CBD', 'mitchellsplaincbd', 'mitchells-plain-khayelitsha'),
	('montclair', 'MONTCLAIR', 'montclair', 'mitchells-plain-khayelitsha'),
	('monwabisi', 'MONWABISI', 'monwabisi', 'mitchells-plain-khayelitsha'),
	('morgans-village', 'MORGANS VILLAGE', 'morgansvillage', 'mitchells-plain-khayelitsha'),
	('mxolisi-phetani', 'MXOLISI PHETANI', 'mxolisiphetani', 'mitchells-plain-khayelitsha'),
	('new-woodlands', 'NEW WOODLANDS', 'newwoodlands', 'mitchells-plain-khayelitsha'),
	('nonqubela', 'NONQUBELA', 'nonqubela', 'mitchells-plain-khayelitsha'),
	('penhill', 'PENHILL', 'penhill', 'mitchells-plain-khayelitsha'),
	('philippi', 'PHILIPPI', 'philippi', 'mitchells-plain-khayelitsha'),
	('philippi-park', 'PHILIPPI PARK', 'philippipark', 'mitchells-plain-khayelitsha'),
	('portland', 'PORTLAND', 'portland', 'mitchells-plain-khayelitsha'),
	('rocklands', 'ROCKLANDS', 'rocklands', 'mitchells-plain-khayelitsha'),
	('rondevlei-park', 'RONDEVLEI PARK', 'rondevleipark', 'mitchells-plain-khayelitsha'),
	('rosedale-klein-vlei', 'ROSEDALE - KLEIN VLEI', 'rosedalekleinvlei', 'mitchells-plain-khayelitsha'),
	('rotterdam', 'ROTTERDAM', 'rotterdam', 'mitchells-plain-khayelitsha'),
	('rustdal', 'RUSTDAL', 'rustdal', 'mitchells-plain-khayelitsha'),
	('sabata-dalindyebo-square', 'SABATA DALINDYEBO SQUARE', 'sabatadalindyebosquare', 'mitchells-plain-khayelitsha'),
	('saxenburg-park-1', 'SAXENBURG PARK 1', 'saxenburgpark1', 'mitchells-plain-khayelitsha'),
	('saxenburg-park-2', 'SAXENBURG PARK 2', 'saxenburgpark2', 'mitchells-plain-khayelitsha'),
	('silversands', 'SILVERSANDS', 'silversands', 'mitchells-plain-khayelitsha'),
	('silvertown-khayelitsha', 'SILVERTOWN - KHAYELITSHA', 'silvertownkhayelitsha', 'mitchells-plain-khayelitsha'),
	('stellenbosch-farms-blue-downs', 'STELLENBOSCH FARMS (BLUE DOWNS)', 'stellenboschfarmsbluedowns', 'mitchells-plain-khayelitsha'),
	('sunbird-park', 'SUNBIRD PARK', 'sunbirdpark', 'mitchells-plain-khayelitsha'),
	('tafelsig', 'TAFELSIG', 'tafelsig', 'mitchells-plain-khayelitsha'),
	('the-conifers', 'THE CONIFERS', 'theconifers', 'mitchells-plain-khayelitsha'),
	('thembokwezi', 'THEMBOKWEZI', 'thembokwezi', 'mitchells-plain-khayelitsha'),
	('tuscany-glen', 'TUSCANY GLEN', 'tuscanyglen', 'mitchells-plain-khayelitsha'),
	('umrhabulo-triangle', 'UMRHABULO TRIANGLE', 'umrhabulotriangle', 'mitchells-plain-khayelitsha'),
	('victoria-mxenge', 'VICTORIA MXENGE', 'victoriamxenge', 'mitchells-plain-khayelitsha'),
	('welmoed-cemetery', 'WELMOED CEMETERY', 'welmoedcemetery', 'mitchells-plain-khayelitsha'),
	('welmoed-estate', 'WELMOED ESTATE', 'welmoedestate', 'mitchells-plain-khayelitsha'),
	('weltevreden-valley', 'WELTEVREDEN VALLEY', 'weltevredenvalley', 'mitchells-plain-khayelitsha'),
	('wembley-park', 'WEMBLEY PARK', 'wembleypark', 'mitchells-plain-khayelitsha'),
	('wesbank', 'WESBANK', 'wesbank', 'mitchells-plain-khayelitsha'),
	('westgate', 'WESTGATE', 'westgate', 'mitchells-plain-khayelitsha'),
	('westridge-mitchells-plain', 'WESTRIDGE - MITCHELLS PLAIN', 'westridgemitchellsplain', 'mitchells-plain-khayelitsha'),
	('wildwood', 'WILDWOOD', 'wildwood', 'mitchells-plain-khayelitsha'),
	('wimbledon-estate', 'WIMBLEDON ESTATE', 'wimbledonestate', 'mitchells-plain-khayelitsha'),
	('wolfgat-nature-reserve', 'WOLFGAT NATURE RESERVE', 'wolfgatnaturereserve', 'mitchells-plain-khayelitsha'),
	('woodlands', 'WOODLANDS', 'woodlands', 'mitchells-plain-khayelitsha');
--> statement-breakpoint
INSERT INTO `suburbs` (`id`, `name`, `search_key`, `region_id`) VALUES
	('amanda-glen', 'AMANDA GLEN', 'amandaglen', 'northern'),
	('annandale-farm', 'ANNANDALE FARM', 'annandalefarm', 'northern'),
	('arauna', 'ARAUNA', 'arauna', 'northern'),
	('atlas-gardens-business-park', 'ATLAS GARDENS BUSINESS PARK', 'atlasgardensbusinesspark', 'northern'),
	('aurora', 'AURORA', 'aurora', 'northern'),
	('avalon-estate', 'AVALON ESTATE', 'avalonestate', 'northern'),
	('belmont-park', 'BELMONT PARK', 'belmontpark', 'northern'),
	('bethanie', 'BETHANIE', 'bethanie', 'northern'),
	('bloekombos', 'BLOEKOMBOS', 'bloekombos', 'northern'),
	('bloemhof', 'BLOEMHOF', 'bloemhof', 'northern'),
	('blomvlei', 'BLOMVLEI', 'blomvlei', 'northern'),
	('bo-oakdale', 'BO OAKDALE', 'booakdale', 'northern'),
	('bonnie-brae', 'BONNIE BRAE', 'bonniebrae', 'northern'),
	('bonnie-brook', 'BONNIE BROOK', 'bonniebrook', 'northern'),
	('botfontein-smallholdings', 'BOTFONTEIN SMALLHOLDINGS', 'botfonteinsmallholdings', 'northern'),
	('bracken-heights', 'BRACKEN HEIGHTS', 'brackenheights', 'northern'),
	('brackenfell-central', 'BRACKENFELL CENTRAL', 'brackenfellcentral', 'northern'),
	('brackenfell-industria', 'BRACKENFELL INDUSTRIA', 'brackenfellindustria', 'northern'),
	('brackenfell-south', 'BRACKENFELL SOUTH', 'brackenfellsouth', 'northern'),
	('brentwood-park-durbanville', 'BRENTWOOD PARK - DURBANVILLE', 'brentwoodparkdurbanville', 'northern'),
	('buh-rein-estate', 'BUH-REIN ESTATE', 'buhreinestate', 'northern'),
	('burgundy', 'BURGUNDY', 'burgundy', 'northern'),
	('cape-farms-district-c', 'CAPE FARMS - DISTRICT C', 'capefarmsdistrictc', 'northern'),
	('cape-gate', 'CAPE GATE', 'capegate', 'northern'),
	('chantecler', 'CHANTECLER', 'chantecler', 'northern'),
	('clara-anna-fontein', 'CLARA ANNA FONTEIN', 'claraannafontein', 'northern'),
	('d-urbanvale', 'D''URBANVALE', 'durbanvale', 'northern'),
	('de-bron', 'DE BRON', 'debron', 'northern'),
	('de-oude-spruit', 'DE OUDE SPRUIT', 'deoudespruit', 'northern'),
	('door-de-kraal', 'DOOR DE KRAAL', 'doordekraal', 'northern'),
	('door-de-kraal-farm', 'DOOR DE KRAAL FARM', 'doordekraalfarm', 'northern'),
	('durbanville', 'DURBANVILLE', 'durbanville', 'northern'),
	('durbanville-hills', 'DURBANVILLE HILLS', 'durbanvillehills', 'northern'),
	('durbanville-meadows', 'DURBANVILLE MEADOWS', 'durbanvillemeadows', 'northern'),
	('durbell', 'DURBELL', 'durbell', 'northern'),
	('durmonte', 'DURMONTE', 'durmonte', 'northern'),
	('edenpark', 'EDENPARK', 'edenpark', 'northern'),
	('eikendal', 'EIKENDAL', 'eikendal', 'northern'),
	('everglen', 'EVERGLEN', 'everglen', 'northern'),
	('everite-industria', 'EVERITE INDUSTRIA', 'everiteindustria', 'northern'),
	('eversdal', 'EVERSDAL', 'eversdal', 'northern'),
	('eversdal-heights', 'EVERSDAL HEIGHTS', 'eversdalheights', 'northern'),
	('ferndale', 'FERNDALE', 'ferndale', 'northern'),
	('fisantekraal', 'FISANTEKRAAL', 'fisantekraal', 'northern'),
	('fisantekraal-industrial', 'FISANTEKRAAL INDUSTRIAL', 'fisantekraalindustrial', 'northern'),
	('goedemoed', 'GOEDEMOED', 'goedemoed', 'northern'),
	('goliath-estate', 'GOLIATH ESTATE', 'goliathestate', 'northern'),
	('graanendal', 'GRAANENDAL', 'graanendal', 'northern'),
	('greenville-garden-city', 'GREENVILLE GARDEN CITY', 'greenvillegardencity', 'northern'),
	('hoheizen', 'HOHEIZEN', 'hoheizen', 'northern'),
	('hoogstede', 'HOOGSTEDE', 'hoogstede', 'northern'),
	('joostenbergvlakte-smallholdings', 'JOOSTENBERGVLAKTE SMALLHOLDINGS', 'joostenbergvlaktesmallholdings', 'northern'),
	('kaapsig', 'KAAPSIG', 'kaapsig', 'northern'),
	('kanonberg', 'KANONBERG', 'kanonberg', 'northern'),
	('kenridge', 'KENRIDGE', 'kenridge', 'northern'),
	('kleinbegin', 'KLEINBEGIN', 'kleinbegin', 'northern'),
	('kleinbron', 'KLEINBRON', 'kleinbron', 'northern'),
	('klipheuwel-housing-scheme', 'KLIPHEUWEL HOUSING SCHEME', 'klipheuwelhousingscheme', 'northern'),
	('kraaifontein', 'KRAAIFONTEIN', 'kraaifontein', 'northern'),
	('kraaifontein-east', 'KRAAIFONTEIN EAST', 'kraaifonteineast', 'northern'),
	('kraaifontein-industria', 'KRAAIFONTEIN INDUSTRIA', 'kraaifonteinindustria', 'northern'),
	('langeberg-hoogte', 'LANGEBERG HOOGTE', 'langeberghoogte', 'northern'),
	('langeberg-ridge', 'LANGEBERG RIDGE', 'langebergridge', 'northern'),
	('langeberg-village', 'LANGEBERG VILLAGE', 'langebergvillage', 'northern'),
	('loevenstein', 'LOEVENSTEIN', 'loevenstein', 'northern'),
	('malmesbury-farms', 'MALMESBURY FARMS', 'malmesburyfarms', 'northern'),
	('mikpunt', 'MIKPUNT', 'mikpunt', 'northern'),
	('morgan-industria', 'MORGAN INDUSTRIA', 'morganindustria', 'northern'),
	('morgenster', 'MORGENSTER', 'morgenster', 'northern'),
	('morgenster-heights', 'MORGENSTER HEIGHTS', 'morgensterheights', 'northern'),
	('morningstar', 'MORNINGSTAR', 'morningstar', 'northern'),
	('natures-valley', 'NATURES VALLEY', 'naturesvalley', 'northern'),
	('nerina', 'NERINA', 'nerina', 'northern'),
	('nieuw-maastrecht-1', 'NIEUW MAASTRECHT-1', 'nieuwmaastrecht1', 'northern'),
	('nieuw-maastrecht-2', 'NIEUW MAASTRECHT-2', 'nieuwmaastrecht2', 'northern'),
	('normandie-estate', 'NORMANDIE ESTATE', 'normandieestate', 'northern'),
	('northpine', 'NORTHPINE', 'northpine', 'northern'),
	('o-kennedyville', 'O''KENNEDYVILLE', 'okennedyville', 'northern'),
	('okavango-park', 'OKAVANGO PARK', 'okavangopark', 'northern'),
	('oude-westhof', 'OUDE WESTHOF', 'oudewesthof', 'northern'),
	('paarl-farms', 'PAARL FARMS', 'paarlfarms', 'northern'),
	('peerless-park-east', 'PEERLESS PARK EAST', 'peerlessparkeast', 'northern'),
	('peerless-park-north', 'PEERLESS PARK NORTH', 'peerlessparknorth', 'northern'),
	('peerless-park-west', 'PEERLESS PARK WEST', 'peerlessparkwest', 'northern'),
	('philadelphia', 'PHILADELPHIA', 'philadelphia', 'northern'),
	('pinehurst', 'PINEHURST', 'pinehurst', 'northern'),
	('protea-heights', 'PROTEA HEIGHTS', 'proteaheights', 'northern'),
	('protea-valley', 'PROTEA VALLEY', 'proteavalley', 'northern'),
	('protea-village', 'PROTEA VILLAGE', 'proteavillage', 'northern'),
	('proteaville', 'PROTEAVILLE', 'proteaville', 'northern'),
	('ridgeworth', 'RIDGEWORTH', 'ridgeworth', 'northern'),
	('rosedale-durbanville', 'ROSEDALE - DURBANVILLE', 'rosedaledurbanville', 'northern'),
	('rosendal', 'ROSENDAL', 'rosendal', 'northern'),
	('rosenpark', 'ROSENPARK', 'rosenpark', 'northern'),
	('ruitershoogte', 'RUITERSHOOGTE', 'ruitershoogte', 'northern'),
	('ruwari', 'RUWARI', 'ruwari', 'northern'),
	('schoongezicht', 'SCHOONGEZICHT', 'schoongezicht', 'northern'),
	('scottsdene', 'SCOTTSDENE', 'scottsdene', 'northern'),
	('scottsville', 'SCOTTSVILLE', 'scottsville', 'northern'),
	('selborne', 'SELBORNE', 'selborne', 'northern'),
	('sonkring', 'SONKRING', 'sonkring', 'northern'),
	('sonstraal', 'SONSTRAAL', 'sonstraal', 'northern'),
	('sonstraal-heights', 'SONSTRAAL HEIGHTS', 'sonstraalheights', 'northern'),
	('springbokpark', 'SPRINGBOKPARK', 'springbokpark', 'northern'),
	('springfield', 'SPRINGFIELD', 'springfield', 'northern'),
	('st-michaels', 'ST MICHAELS', 'stmichaels', 'northern'),
	('stellenberg', 'STELLENBERG', 'stellenberg', 'northern'),
	('stellenbosch-univ', 'STELLENBOSCH UNIV', 'stellenboschuniv', 'northern'),
	('stellenridge', 'STELLENRIDGE', 'stellenridge', 'northern'),
	('stellenryk', 'STELLENRYK', 'stellenryk', 'northern'),
	('summerville', 'SUMMERVILLE', 'summerville', 'northern'),
	('the-crest', 'THE CREST', 'thecrest', 'northern'),
	('tygervalley', 'TYGERVALLEY', 'tygervalley', 'northern'),
	('tygervalley-waterfront', 'TYGERVALLEY WATERFRONT', 'tygervalleywaterfront', 'northern'),
	('uitzicht', 'UITZICHT', 'uitzicht', 'northern'),
	('valmary-park', 'VALMARY PARK', 'valmarypark', 'northern'),
	('van-riebeeckshof', 'VAN RIEBEECKSHOF', 'vanriebeeckshof', 'northern'),
	('vergesig', 'VERGESIG', 'vergesig', 'northern'),
	('vierlanden', 'VIERLANDEN', 'vierlanden', 'northern'),
	('viking-village', 'VIKING VILLAGE', 'vikingvillage', 'northern'),
	('vredekloof', 'VREDEKLOOF', 'vredekloof', 'northern'),
	('vredekloof-east', 'VREDEKLOOF EAST', 'vredekloofeast', 'northern'),
	('vredekloof-heights', 'VREDEKLOOF HEIGHTS', 'vredekloofheights', 'northern'),
	('vygeboom', 'VYGEBOOM', 'vygeboom', 'northern'),
	('wairoa', 'WAIROA', 'wairoa', 'northern'),
	('wallacedene', 'WALLACEDENE', 'wallacedene', 'northern'),
	('welgedacht', 'WELGEDACHT', 'welgedacht', 'northern'),
	('welgemoed', 'WELGEMOED', 'welgemoed', 'northern'),
	('welgevonden', 'WELGEVONDEN', 'welgevonden', 'northern'),
	('wellway-park', 'WELLWAY PARK', 'wellwaypark', 'northern'),
	('wellway-park-east', 'WELLWAY PARK EAST', 'wellwayparkeast', 'northern'),
	('westerdale', 'WESTERDALE', 'westerdale', 'northern'),
	('windsor-estate', 'WINDSOR ESTATE', 'windsorestate', 'northern'),
	('windsor-park-estate', 'WINDSOR PARK ESTATE', 'windsorparkestate', 'northern'),
	('wynland-industrial-park', 'WYNLAND INDUSTRIAL PARK', 'wynlandindustrialpark', 'northern'),
	('zoo-park', 'ZOO PARK', 'zoopark', 'northern');
--> statement-breakpoint
INSERT INTO `suburbs` (`id`, `name`, `search_key`, `region_id`) VALUES
	('bergvliet', 'BERGVLIET', 'bergvliet', 'southern'),
	('bishopscourt', 'BISHOPSCOURT', 'bishopscourt', 'southern'),
	('cape-farms-district-h', 'CAPE FARMS - DISTRICT H', 'capefarmsdistricth', 'southern'),
	('castle-rock', 'CASTLE ROCK', 'castlerock', 'southern'),
	('claremont', 'CLAREMONT', 'claremont', 'southern'),
	('clovelly', 'CLOVELLY', 'clovelly', 'southern'),
	('constantia', 'CONSTANTIA', 'constantia', 'southern'),
	('diep-river', 'DIEP RIVER', 'diepriver', 'southern'),
	('elfindale', 'ELFINDALE', 'elfindale', 'southern'),
	('fish-hoek', 'FISH HOEK', 'fishhoek', 'southern'),
	('glencairn', 'GLENCAIRN', 'glencairn', 'southern'),
	('heathfield', 'HEATHFIELD', 'heathfield', 'southern'),
	('hout-bay', 'HOUT BAY', 'houtbay', 'southern'),
	('kalk-bay', 'KALK BAY', 'kalkbay', 'southern'),
	('kenilworth', 'KENILWORTH', 'kenilworth', 'southern'),
	('kirstenhof', 'KIRSTENHOF', 'kirstenhof', 'southern'),
	('kommetjie', 'KOMMETJIE', 'kommetjie', 'southern'),
	('lakeside', 'LAKESIDE', 'lakeside', 'southern'),
	('llandudno', 'LLANDUDNO', 'llandudno', 'southern'),
	('meadowridge', 'MEADOWRIDGE', 'meadowridge', 'southern'),
	('misty-cliffs', 'MISTY CLIFFS', 'mistycliffs', 'southern'),
	('mowbray', 'MOWBRAY', 'mowbray', 'southern'),
	('muizenberg', 'MUIZENBERG', 'muizenberg', 'southern'),
	('newlands', 'NEWLANDS', 'newlands', 'southern'),
	('noordhoek', 'NOORDHOEK', 'noordhoek', 'southern'),
	('ocean-view', 'OCEAN VIEW', 'oceanview', 'southern'),
	('plumstead', 'PLUMSTEAD', 'plumstead', 'southern'),
	('retreat', 'RETREAT', 'retreat', 'southern'),
	('rondebosch', 'RONDEBOSCH', 'rondebosch', 'southern'),
	('rosebank', 'ROSEBANK', 'rosebank', 'southern'),
	('scarborough', 'SCARBOROUGH', 'scarborough', 'southern'),
	('simon-s-town', 'SIMON''S TOWN', 'simonstown', 'southern'),
	('smitswinkelbaai', 'SMITSWINKELBAAI', 'smitswinkelbaai', 'southern'),
	('southfield', 'SOUTHFIELD', 'southfield', 'southern'),
	('st-james', 'ST JAMES', 'stjames', 'southern'),
	('steenberg', 'STEENBERG', 'steenberg', 'southern'),
	('sun-valley', 'SUN VALLEY', 'sunvalley', 'southern'),
	('sunnydale', 'SUNNYDALE', 'sunnydale', 'southern'),
	('table-mountain', 'TABLE MOUNTAIN', 'tablemountain', 'southern'),
	('tokai', 'TOKAI', 'tokai', 'southern'),
	('westlake', 'WESTLAKE', 'westlake', 'southern'),
	('wynberg', 'WYNBERG', 'wynberg', 'southern'),
	('wynberg-nu', 'WYNBERG NU', 'wynbergnu', 'southern');
--> statement-breakpoint
INSERT INTO `suburbs` (`id`, `name`, `search_key`, `region_id`) VALUES
	('acacia-park', 'ACACIA PARK', 'acaciapark', 'table-bay'),
	('bantry-bay', 'BANTRY BAY', 'bantrybay', 'table-bay'),
	('bo-kaap', 'BO-KAAP', 'bokaap', 'table-bay'),
	('camps-bay-bakoven', 'CAMPS BAY / BAKOVEN', 'campsbaybakoven', 'table-bay'),
	('cape-town-city-centre', 'CAPE TOWN CITY CENTRE', 'capetowncitycentre', 'table-bay'),
	('clifton', 'CLIFTON', 'clifton', 'table-bay'),
	('district-six', 'DISTRICT SIX', 'districtsix', 'table-bay'),
	('epping-industria-1', 'EPPING INDUSTRIA 1', 'eppingindustria1', 'table-bay'),
	('foreshore', 'FORESHORE', 'foreshore', 'table-bay'),
	('fresnaye', 'FRESNAYE', 'fresnaye', 'table-bay'),
	('gardens', 'GARDENS', 'gardens', 'table-bay'),
	('green-point', 'GREEN POINT', 'greenpoint', 'table-bay'),
	('kensington', 'KENSINGTON', 'kensington', 'table-bay'),
	('langa', 'LANGA', 'langa', 'table-bay'),
	('maitland', 'MAITLAND', 'maitland', 'table-bay'),
	('maitland-garden-village', 'MAITLAND GARDEN VILLAGE', 'maitlandgardenvillage', 'table-bay'),
	('mouille-point', 'MOUILLE POINT', 'mouillepoint', 'table-bay'),
	('observatory', 'OBSERVATORY', 'observatory', 'table-bay'),
	('oranjezicht', 'ORANJEZICHT', 'oranjezicht', 'table-bay'),
	('oudekraal', 'OUDEKRAAL', 'oudekraal', 'table-bay'),
	('paarden-eiland', 'PAARDEN EILAND', 'paardeneiland', 'table-bay'),
	('pinelands', 'PINELANDS', 'pinelands', 'table-bay'),
	('robben-island', 'ROBBEN ISLAND', 'robbenisland', 'table-bay'),
	('salt-river', 'SALT RIVER', 'saltriver', 'table-bay'),
	('sea-point', 'SEA POINT', 'seapoint', 'table-bay'),
	('signal-hill-lions-head', 'SIGNAL HILL / LIONS HEAD', 'signalhilllionshead', 'table-bay'),
	('tamboerskloof', 'TAMBOERSKLOOF', 'tamboerskloof', 'table-bay'),
	('thornton', 'THORNTON', 'thornton', 'table-bay'),
	('three-anchor-bay', 'THREE ANCHOR BAY', 'threeanchorbay', 'table-bay'),
	('vredehoek', 'VREDEHOEK', 'vredehoek', 'table-bay'),
	('windermere', 'WINDERMERE', 'windermere', 'table-bay'),
	('wingfield', 'WINGFIELD', 'wingfield', 'table-bay'),
	('woodstock', 'WOODSTOCK', 'woodstock', 'table-bay');
--> statement-breakpoint
INSERT INTO `suburbs` (`id`, `name`, `search_key`, `region_id`) VALUES
	('adriaanse', 'ADRIAANSE', 'adriaanse', 'tygerberg'),
	('airport-city', 'AIRPORT CITY', 'airportcity', 'tygerberg'),
	('amandelrug', 'AMANDELRUG', 'amandelrug', 'tygerberg'),
	('amandelsig', 'AMANDELSIG', 'amandelsig', 'tygerberg'),
	('annandale', 'ANNANDALE', 'annandale', 'tygerberg'),
	('avon', 'AVON', 'avon', 'tygerberg'),
	('avondale-parow', 'AVONDALE - PAROW', 'avondaleparow', 'tygerberg'),
	('avonwood', 'AVONWOOD', 'avonwood', 'tygerberg'),
	('balvenie', 'BALVENIE', 'balvenie', 'tygerberg'),
	('baronetcy-estate', 'BARONETCY ESTATE', 'baronetcyestate', 'tygerberg'),
	('beaconvale', 'BEACONVALE', 'beaconvale', 'tygerberg'),
	('belgravia-bellville', 'BELGRAVIA -BELLVILLE', 'belgraviabellville', 'tygerberg'),
	('belhar-ext-1', 'BELHAR EXT 1', 'belharext1', 'tygerberg'),
	('belhar-ext-10', 'BELHAR EXT 10', 'belharext10', 'tygerberg'),
	('belhar-ext-11', 'BELHAR EXT 11', 'belharext11', 'tygerberg'),
	('belhar-ext-12', 'BELHAR EXT 12', 'belharext12', 'tygerberg'),
	('belhar-ext-13', 'BELHAR EXT 13', 'belharext13', 'tygerberg'),
	('belhar-ext-14', 'BELHAR EXT 14', 'belharext14', 'tygerberg'),
	('belhar-ext-15', 'BELHAR EXT 15', 'belharext15', 'tygerberg'),
	('belhar-ext-16', 'BELHAR EXT 16', 'belharext16', 'tygerberg'),
	('belhar-ext-17', 'BELHAR EXT 17', 'belharext17', 'tygerberg'),
	('belhar-ext-18', 'BELHAR EXT 18', 'belharext18', 'tygerberg'),
	('belhar-ext-19', 'BELHAR EXT 19', 'belharext19', 'tygerberg'),
	('belhar-ext-2', 'BELHAR EXT 2', 'belharext2', 'tygerberg'),
	('belhar-ext-20', 'BELHAR EXT 20', 'belharext20', 'tygerberg'),
	('belhar-ext-21', 'BELHAR EXT 21', 'belharext21', 'tygerberg'),
	('belhar-ext-22', 'BELHAR EXT 22', 'belharext22', 'tygerberg'),
	('belhar-ext-23', 'BELHAR EXT 23', 'belharext23', 'tygerberg'),
	('belhar-ext-3', 'BELHAR EXT 3', 'belharext3', 'tygerberg'),
	('belhar-ext-4', 'BELHAR EXT 4', 'belharext4', 'tygerberg'),
	('belhar-ext-5', 'BELHAR EXT 5', 'belharext5', 'tygerberg'),
	('belhar-ext-6', 'BELHAR EXT 6', 'belharext6', 'tygerberg'),
	('belhar-ext-7', 'BELHAR EXT 7', 'belharext7', 'tygerberg'),
	('belhar-ext-8', 'BELHAR EXT 8', 'belharext8', 'tygerberg'),
	('belhar-ext-9', 'BELHAR EXT 9', 'belharext9', 'tygerberg'),
	('bellair', 'BELLAIR', 'bellair', 'tygerberg'),
	('bellville-cbd', 'BELLVILLE CBD', 'bellvillecbd', 'tygerberg'),
	('bellville-landfill', 'BELLVILLE LANDFILL', 'bellvillelandfill', 'tygerberg'),
	('bellville-south', 'BELLVILLE SOUTH', 'bellvillesouth', 'tygerberg'),
	('bellville-south-industria', 'BELLVILLE SOUTH INDUSTRIA', 'bellvillesouthindustria', 'tygerberg'),
	('bellville-teachers-college', 'BELLVILLE TEACHERS COLLEGE', 'bellvilleteacherscollege', 'tygerberg'),
	('belrail', 'BELRAIL', 'belrail', 'tygerberg'),
	('belvedere-tygerberg', 'BELVEDERE TYGERBERG', 'belvederetygerberg', 'tygerberg'),
	('benno-park', 'BENNO PARK', 'bennopark', 'tygerberg'),
	('bishop-lavis', 'BISHOP LAVIS', 'bishoplavis', 'tygerberg'),
	('blommendal', 'BLOMMENDAL', 'blommendal', 'tygerberg'),
	('blomtuin', 'BLOMTUIN', 'blomtuin', 'tygerberg'),
	('bonteheuwel', 'BONTEHEUWEL', 'bonteheuwel', 'tygerberg'),
	('boquinar-industrial-area', 'BOQUINAR INDUSTRIAL AREA', 'boquinarindustrialarea', 'tygerberg'),
	('bosbell', 'BOSBELL', 'bosbell', 'tygerberg'),
	('bosonia', 'BOSONIA', 'bosonia', 'tygerberg'),
	('boston', 'BOSTON', 'boston', 'tygerberg'),
	('bothasig', 'BOTHASIG', 'bothasig', 'tygerberg'),
	('bottelary-smallholdings-1', 'BOTTELARY SMALLHOLDINGS 1', 'bottelarysmallholdings1', 'tygerberg'),
	('bottelary-smallholdings-2', 'BOTTELARY SMALLHOLDINGS 2', 'bottelarysmallholdings2', 'tygerberg'),
	('brackenfell-common', 'BRACKENFELL COMMON', 'brackenfellcommon', 'tygerberg'),
	('brandwag', 'BRANDWAG', 'brandwag', 'tygerberg'),
	('brantwood', 'BRANTWOOD', 'brantwood', 'tygerberg'),
	('burgundy-estate', 'BURGUNDY ESTATE', 'burgundyestate', 'tygerberg'),
	('cape-town-airport', 'CAPE TOWN AIRPORT', 'capetownairport', 'tygerberg'),
	('charlesville', 'CHARLESVILLE', 'charlesville', 'tygerberg'),
	('chrismar', 'CHRISMAR', 'chrismar', 'tygerberg'),
	('churchill-estate', 'CHURCHILL ESTATE', 'churchillestate', 'tygerberg'),
	('clamhall', 'CLAMHALL', 'clamhall', 'tygerberg'),
	('clarkes-estate', 'CLARKES ESTATE', 'clarkesestate', 'tygerberg'),
	('connaught', 'CONNAUGHT', 'connaught', 'tygerberg'),
	('cput', 'CPUT', 'cput', 'tygerberg'),
	('cravenby', 'CRAVENBY', 'cravenby', 'tygerberg'),
	('danarand', 'DANARAND', 'danarand', 'tygerberg'),
	('de-duin', 'DE DUIN', 'deduin', 'tygerberg'),
	('de-grendel-farm', 'DE GRENDEL FARM', 'degrendelfarm', 'tygerberg'),
	('de-kuilen', 'DE KUILEN', 'dekuilen', 'tygerberg'),
	('de-la-haye', 'DE LA HAYE', 'delahaye', 'tygerberg'),
	('de-tijger', 'DE TIJGER', 'detijger', 'tygerberg'),
	('delft-1-2', 'DELFT 1 & 2', 'delft12', 'tygerberg'),
	('delft-3', 'DELFT 3', 'delft3', 'tygerberg'),
	('delft-4', 'DELFT 4', 'delft4', 'tygerberg'),
	('delft-5', 'DELFT 5', 'delft5', 'tygerberg'),
	('delft-6', 'DELFT 6', 'delft6', 'tygerberg'),
	('delft-7', 'DELFT 7', 'delft7', 'tygerberg'),
	('delft-8', 'DELFT 8', 'delft8', 'tygerberg'),
	('delft-9', 'DELFT 9', 'delft9', 'tygerberg'),
	('delft-south', 'DELFT SOUTH', 'delftsouth', 'tygerberg'),
	('des-hampden', 'DES HAMPDEN', 'deshampden', 'tygerberg'),
	('dunrobin', 'DUNROBIN', 'dunrobin', 'tygerberg'),
	('edgemead', 'EDGEMEAD', 'edgemead', 'tygerberg'),
	('eensgevonden', 'EENSGEVONDEN', 'eensgevonden', 'tygerberg'),
	('eikenbosch-kuils-river', 'EIKENBOSCH KUILS RIVER', 'eikenboschkuilsriver', 'tygerberg'),
	('eindhoven', 'EINDHOVEN', 'eindhoven', 'tygerberg'),
	('elim', 'ELIM', 'elim', 'tygerberg'),
	('elnor', 'ELNOR', 'elnor', 'tygerberg'),
	('elsies-river', 'ELSIES RIVER', 'elsiesriver', 'tygerberg'),
	('elsies-river-industria', 'ELSIES RIVER INDUSTRIA', 'elsiesriverindustria', 'tygerberg'),
	('epping-forest', 'EPPING FOREST', 'eppingforest', 'tygerberg'),
	('epping-industria-2', 'EPPING INDUSTRIA 2', 'eppingindustria2', 'tygerberg'),
	('eureka-estate', 'EUREKA ESTATE', 'eurekaestate', 'tygerberg'),
	('fairfield-estate', 'FAIRFIELD ESTATE', 'fairfieldestate', 'tygerberg'),
	('florida', 'FLORIDA', 'florida', 'tygerberg'),
	('gersham', 'GERSHAM', 'gersham', 'tygerberg'),
	('glenhaven', 'GLENHAVEN', 'glenhaven', 'tygerberg'),
	('glenlily', 'GLENLILY', 'glenlily', 'tygerberg'),
	('glenwood', 'GLENWOOD', 'glenwood', 'tygerberg'),
	('goodrail', 'GOODRAIL', 'goodrail', 'tygerberg'),
	('goodwood-estate', 'GOODWOOD ESTATE', 'goodwoodestate', 'tygerberg'),
	('goodwood-ext-1', 'GOODWOOD EXT 1', 'goodwoodext1', 'tygerberg'),
	('greenlands', 'GREENLANDS', 'greenlands', 'tygerberg'),
	('groenvallei', 'GROENVALLEI', 'groenvallei', 'tygerberg'),
	('haasendal', 'HAASENDAL', 'haasendal', 'tygerberg'),
	('hardekraaltjie', 'HARDEKRAALTJIE', 'hardekraaltjie', 'tygerberg'),
	('heemstede', 'HEEMSTEDE', 'heemstede', 'tygerberg'),
	('highbury', 'HIGHBURY', 'highbury', 'tygerberg'),
	('highbury-park', 'HIGHBURY PARK', 'highburypark', 'tygerberg'),
	('hunters-creek', 'HUNTERS CREEK', 'hunterscreek', 'tygerberg'),
	('jacarandas', 'JACARANDAS', 'jacarandas', 'tygerberg'),
	('jagtershof', 'JAGTERSHOF', 'jagtershof', 'tygerberg'),
	('jan-kriel', 'JAN KRIEL', 'jankriel', 'tygerberg'),
	('joubertpark', 'JOUBERTPARK', 'joubertpark', 'tygerberg'),
	('kaapzicht', 'KAAPZICHT', 'kaapzicht', 'tygerberg'),
	('kalkfontein', 'KALKFONTEIN', 'kalkfontein', 'tygerberg'),
	('kalksteenfontein', 'KALKSTEENFONTEIN', 'kalksteenfontein', 'tygerberg'),
	('kempenville', 'KEMPENVILLE', 'kempenville', 'tygerberg'),
	('king-david-country-club', 'KING DAVID COUNTRY CLUB', 'kingdavidcountryclub', 'tygerberg'),
	('kingston', 'KINGSTON', 'kingston', 'tygerberg'),
	('klein-zevenwacht', 'KLEIN ZEVENWACHT', 'kleinzevenwacht', 'tygerberg'),
	('kleinbosch', 'KLEINBOSCH', 'kleinbosch', 'tygerberg'),
	('klipdam', 'KLIPDAM', 'klipdam', 'tygerberg'),
	('klipkop', 'KLIPKOP', 'klipkop', 'tygerberg'),
	('kloofzicht', 'KLOOFZICHT', 'kloofzicht', 'tygerberg'),
	('kuils-river-common', 'KUILS RIVER COMMON', 'kuilsrivercommon', 'tygerberg'),
	('kuils-river-sports-grounds', 'KUILS RIVER SPORTS GROUNDS', 'kuilsriversportsgrounds', 'tygerberg'),
	('kuilsrivier-golf-course', 'KUILSRIVIER GOLF COURSE', 'kuilsriviergolfcourse', 'tygerberg'),
	('kuilsrivier-industria', 'KUILSRIVIER INDUSTRIA', 'kuilsrivierindustria', 'tygerberg'),
	('kuilsrivier-south-smallholdings', 'KUILSRIVIER SOUTH SMALLHOLDINGS', 'kuilsriviersouthsmallholdings', 'tygerberg'),
	('la-rochelle', 'LA ROCHELLE', 'larochelle', 'tygerberg'),
	('labiance', 'LABIANCE', 'labiance', 'tygerberg'),
	('leiden', 'LEIDEN', 'leiden', 'tygerberg'),
	('leonsdale', 'LEONSDALE', 'leonsdale', 'tygerberg'),
	('letru', 'LETRU', 'letru', 'tygerberg'),
	('lillydale', 'LILLYDALE', 'lillydale', 'tygerberg'),
	('loucharmante', 'LOUCHARMANTE', 'loucharmante', 'tygerberg'),
	('loumar', 'LOUMAR', 'loumar', 'tygerberg'),
	('mabille-park', 'MABILLE PARK', 'mabillepark', 'tygerberg'),
	('marinda-park', 'MARINDA PARK', 'marindapark', 'tygerberg'),
	('matroosfontein', 'MATROOSFONTEIN', 'matroosfontein', 'tygerberg'),
	('meyerhof', 'MEYERHOF', 'meyerhof', 'tygerberg'),
	('mikro-park', 'MIKRO PARK', 'mikropark', 'tygerberg'),
	('modderdam', 'MODDERDAM', 'modderdam', 'tygerberg'),
	('montague', 'MONTAGUE', 'montague', 'tygerberg'),
	('montana', 'MONTANA', 'montana', 'tygerberg'),
	('montana-extension', 'MONTANA EXTENSION', 'montanaextension', 'tygerberg'),
	('monte-vista', 'MONTE VISTA', 'montevista', 'tygerberg'),
	('montevideo', 'MONTEVIDEO', 'montevideo', 'tygerberg'),
	('n1-stad', 'N1-STAD', 'n1stad', 'tygerberg'),
	('nooitgedacht', 'NOOITGEDACHT', 'nooitgedacht', 'tygerberg'),
	('northgate', 'NORTHGATE', 'northgate', 'tygerberg'),
	('oakdale', 'OAKDALE', 'oakdale', 'tygerberg'),
	('oakdene', 'OAKDENE', 'oakdene', 'tygerberg'),
	('oakglen', 'OAKGLEN', 'oakglen', 'tygerberg'),
	('oosterzee-bellville', 'OOSTERZEE-BELLVILLE', 'oosterzeebellville', 'tygerberg'),
	('panorama', 'PANORAMA', 'panorama', 'tygerberg'),
	('parow', 'PAROW', 'parow', 'tygerberg'),
	('parow-east', 'PAROW EAST', 'paroweast', 'tygerberg'),
	('parow-golf-course', 'PAROW GOLF COURSE', 'parowgolfcourse', 'tygerberg'),
	('parow-industria', 'PAROW INDUSTRIA', 'parowindustria', 'tygerberg'),
	('parow-north', 'PAROW NORTH', 'parownorth', 'tygerberg'),
	('parow-valley', 'PAROW VALLEY', 'parowvalley', 'tygerberg'),
	('petrosa-tank-farm', 'PETROSA TANK FARM', 'petrosatankfarm', 'tygerberg'),
	('plattekloof-1', 'PLATTEKLOOF 1', 'plattekloof1', 'tygerberg'),
	('plattekloof-2', 'PLATTEKLOOF 2', 'plattekloof2', 'tygerberg'),
	('plattekloof-3', 'PLATTEKLOOF 3', 'plattekloof3', 'tygerberg'),
	('plattekloof-glen', 'PLATTEKLOOF GLEN', 'plattekloofglen', 'tygerberg'),
	('ravensmead', 'RAVENSMEAD', 'ravensmead', 'tygerberg'),
	('richmond', 'RICHMOND', 'richmond', 'tygerberg'),
	('richmond-estate', 'RICHMOND ESTATE', 'richmondestate', 'tygerberg'),
	('richmond-park', 'RICHMOND PARK', 'richmondpark', 'tygerberg'),
	('richwood', 'RICHWOOD', 'richwood', 'tygerberg'),
	('riverton-elsies-river', 'RIVERTON ELSIES RIVER', 'rivertonelsiesriver', 'tygerberg'),
	('roosendal', 'ROOSENDAL', 'roosendal', 'tygerberg'),
	('rouxville', 'ROUXVILLE', 'rouxville', 'tygerberg'),
	('ruyterwacht', 'RUYTERWACHT', 'ruyterwacht', 'tygerberg'),
	('sack-s-circle-industria', 'SACK''S CIRCLE INDUSTRIA', 'sackscircleindustria', 'tygerberg'),
	('sanlamhof', 'SANLAMHOF', 'sanlamhof', 'tygerberg'),
	('sarepta', 'SAREPTA', 'sarepta', 'tygerberg'),
	('saxon-industrial', 'SAXON INDUSTRIAL', 'saxonindustrial', 'tygerberg'),
	('shirley-park', 'SHIRLEY PARK', 'shirleypark', 'tygerberg'),
	('silveroaks', 'SILVEROAKS', 'silveroaks', 'tygerberg'),
	('sirrocco-s', 'SIRROCCO''S', 'sirroccos', 'tygerberg'),
	('soneike-i', 'SONEIKE I', 'soneikei', 'tygerberg'),
	('soneike-ii', 'SONEIKE II', 'soneikeii', 'tygerberg'),
	('sonnekuil', 'SONNEKUIL', 'sonnekuil', 'tygerberg'),
	('sonnendal', 'SONNENDAL', 'sonnendal', 'tygerberg'),
	('st-dumas', 'ST DUMAS', 'stdumas', 'tygerberg'),
	('stellenbosch-farms-kuilsrivier', 'STELLENBOSCH FARMS (KUILSRIVIER)', 'stellenboschfarmskuilsrivier', 'tygerberg'),
	('stellendale', 'STELLENDALE', 'stellendale', 'tygerberg'),
	('stikland', 'STIKLAND', 'stikland', 'tygerberg'),
	('stikland-hospitaal', 'STIKLAND HOSPITAAL', 'stiklandhospitaal', 'tygerberg'),
	('stikland-industria', 'STIKLAND INDUSTRIA', 'stiklandindustria', 'tygerberg'),
	('the-hague', 'THE HAGUE', 'thehague', 'tygerberg'),
	('the-range', 'THE RANGE', 'therange', 'tygerberg'),
	('townsend-estate', 'TOWNSEND ESTATE', 'townsendestate', 'tygerberg'),
	('transnet-marshalling-yard', 'TRANSNET MARSHALLING YARD', 'transnetmarshallingyard', 'tygerberg'),
	('triangle-farm', 'TRIANGLE FARM', 'trianglefarm', 'tygerberg'),
	('turtle-creek', 'TURTLE CREEK', 'turtlecreek', 'tygerberg'),
	('tygerberg-hospital', 'TYGERBERG HOSPITAL', 'tygerberghospital', 'tygerberg'),
	('tygerdal', 'TYGERDAL', 'tygerdal', 'tygerberg'),
	('uitsig', 'UITSIG', 'uitsig', 'tygerberg'),
	('uwc', 'UWC', 'uwc', 'tygerberg'),
	('valhalla-park', 'VALHALLA PARK', 'valhallapark', 'tygerberg'),
	('vasco-estate', 'VASCO ESTATE', 'vascoestate', 'tygerberg'),
	('voelvlei', 'VOELVLEI', 'voelvlei', 'tygerberg'),
	('vogelvlei', 'VOGELVLEI', 'vogelvlei', 'tygerberg'),
	('voorbrug', 'VOORBRUG', 'voorbrug', 'tygerberg'),
	('vredelust-bellville', 'VREDELUST BELLVILLE', 'vredelustbellville', 'tygerberg'),
	('vredelust-kuils-river', 'VREDELUST KUILS RIVER', 'vredelustkuilsriver', 'tygerberg'),
	('vredenberg-bellville', 'VREDENBERG - BELLVILLE', 'vredenbergbellville', 'tygerberg'),
	('welgelegen', 'WELGELEGEN', 'welgelegen', 'tygerberg'),
	('wp-park', 'WP PARK', 'wppark', 'tygerberg'),
	('wp-showgrounds', 'WP SHOWGROUNDS', 'wpshowgrounds', 'tygerberg'),
	('zevendal', 'ZEVENDAL', 'zevendal', 'tygerberg'),
	('zevenwacht-country-estate', 'ZEVENWACHT COUNTRY ESTATE', 'zevenwachtcountryestate', 'tygerberg'),
	('zevenwacht-farm-village', 'ZEVENWACHT FARM VILLAGE', 'zevenwachtfarmvillage', 'tygerberg'),
	('zevenwacht-mall', 'ZEVENWACHT MALL', 'zevenwachtmall', 'tygerberg'),
	('zevenwacht-retirement-village', 'ZEVENWACHT RETIREMENT VILLAGE', 'zevenwachtretirementvillage', 'tygerberg'),
	('zevenzicht', 'ZEVENZICHT', 'zevenzicht', 'tygerberg');
