import { EMAIL_CODE } from "@/domain/accounts/inputs";

// Every word the web app shows, in one place for later translation. Copy is a
// placeholder until final copy is written (#111).

export const copy = {
  appName: "ArtisanConnect",
  header: {
    visitor: { findArtisans: "Find Artisans", signUp: "Sign up", signIn: "Sign in" },
    client: { jobs: "Jobs", findArtisans: "Find Artisans", account: "Account" },
    artisan: { home: "Home", profile: "Profile", payouts: "Payouts", account: "Account" },
    admin: { queues: "Queues", admins: "Admins", audit: "Audit log", signOut: "Sign out" },
    notices: "Notices",
  },
  landing: {
    title: "Hire a verified Artisan in Cape Town",
    lead: "Post a Job, compare fixed-price Quotes, and pay through the platform. The money waits with the platform until the work is done.",
    postJob: "Post a Job",
    findArtisans: "Find Artisans",
    signIn: "I have an Account",
    howTitle: "How a Job goes",
    how: [
      {
        title: "Post a Job",
        text: "Describe the work, pick your suburb, and add photos. Your street stays private until you hire.",
      },
      {
        title: "Compare Quotes",
        text: "Up to five verified Artisans send a fixed price: Labour, Materials, start date, and any Warranty they offer.",
      },
      {
        title: "Hire by paying",
        text: "You pay the Quote through the platform, which holds it. Nobody is paid in cash or off the platform.",
      },
      {
        title: "Approve the work",
        text: "The Materials go to the Artisan when work starts on site; the Labour once you approve the work.",
      },
    ],
    tradesTitle: "Eight trades",
    tradesLead: "Browse the Artisans verified for each one, by Region.",
    feesTitle: "Fees shown before you pay",
    fees: "A Quote is the Artisan's fixed price. When you hire, you see the 5% Protection Fee on top before you pay, and nothing is added after.",
    badgeTitle: "A badge is a check, not a guarantee",
    badge:
      "Each Verification Badge is a document the Admin checked, such as an identity document or a trade registration. It is not a promise that the work will be good: read the Reviews too.",
  },
  browse: {
    title: "Find Artisans",
    lead: "Verified Artisans, one trade at a time. Those Available for Jobs come first, then by name. Nobody pays to be higher.",
    chooseTrade: "Choose a trade",
    trade: "Trade",
    region: "Region",
    allRegions: "All Regions",
    count: (count: number) => (count === 1 ? "1 Artisan" : `${count} Artisans`),
    empty: "No Artisan is verified for this trade here yet.",
    available: "Available for Jobs",
    notAvailable: "Not taking Job Matches now",
    gasWork: "Gas work too",
    noRegions: "No Regions chosen yet",
    open: "Open Profile",
    signUpPrompt: "To post a Job or invite an Artisan to Quote, sign up as a Client.",
    signUp: "Sign up",
  },
  profile: {
    about: "About",
    noAbout: "No About text yet.",
    photos: "Work photos",
    noPhotos: "No work photos yet.",
    photo: (index: number) => `Work photo ${index}`,
    gasWork: "gas work too",
    badges: "Verification Badges",
    badgesNote: "A badge is a check the Admin accepted, not a promise that the work will be good.",
    expires: (day: string) => `expires ${day}`,
    issued: (day: string) => `issued ${day}`,
    regions: "Works in",
    noRegions: "No Regions chosen yet.",
    available: "Available for Jobs",
    notAvailable: "Not taking Job Matches now",
    completed: (count: number) => (count === 1 ? "1 Job Completed" : `${count} Jobs Completed`),
    rating: (average: number, count: number) =>
      `${average.toFixed(1)} out of 5, from ${count} ${count === 1 ? "Review" : "Reviews"}`,
    noRating: "No Reviews yet",
    reviews: "Reviews",
    noReviews: "No Reviews yet. A Client reviews an Artisan once a Job is Completed.",
    noContact:
      "Work is arranged on ArtisanConnect, so a Profile shows no phone number, email, or address.",
    inviteTitle: (name: string) => `Want ${name} to Quote?`,
    inviteLead:
      "Sign up as a Client to post a Job and invite Artisans to Quote. You hire by paying through the platform.",
    signUp: "Sign up",
    signIn: "Sign in",
    share: "Copy the link to this Profile",
    copied: "Link copied",
    back: "Find Artisans",
    description: (name: string, categories: string[]) =>
      `${name}: ${categories.join(", ")} in Cape Town, verified on ArtisanConnect.`,
    notFound: "No such Profile",
    notFoundLead:
      "This Artisan is not on ArtisanConnect, or is not verified for any trade right now.",
  },
  myProfile: {
    title: "Profile",
    lead: "Your public page. Every edit waits for the Admin, and your Profile shows the version before it until then.",
    notPublic:
      "Nobody else can open your Profile until you are verified for a Service Category. You can prepare it now.",
    open: "Open your public Profile",
    edit: "Edit Profile",
    about: "About",
    aboutHint: (max: number) =>
      `What you do and how you work, up to ${max} characters. No phone number, email, link, or address: work is arranged on the platform.`,
    photos: "Work photos",
    photosHint: (max: number) =>
      `Up to ${max} photos of your own finished work (JPEG, PNG, or WebP, up to 10 MB each).`,
    remove: "Remove",
    restore: "Keep",
    send: "Send to the Admin",
    cancel: "Cancel",
    sent: "Sent. The Admin checks it, and we tell you the outcome. Your Profile shows the version before it until then.",
    beingChecked: "Being checked",
    beingCheckedLead:
      "This edit waits for the Admin. Until then, everyone sees your Profile as it is above.",
    withdraw: "Withdraw",
    refused: (reason: string) => `Your last edit was refused: ${reason}`,
    preview: "As anyone sees it",
  },
  signUp: {
    title: "Sign up",
    kind: {
      step: "Client or Artisan",
      client: "I need work done",
      clientHint: "A Client posts Jobs and hires Artisans.",
      artisan: "I do the work",
      artisanHint: "An Artisan sends Quotes once verified.",
      fixed: "You choose once. To do both, sign up again with another Email.",
      chosen: { client: "Client", artisan: "Artisan" },
    },
    names: {
      step: "Your name",
      name: "Full name",
      tradingName: "Trading name (optional)",
      clientHint: "Artisans see a Client as first name and last initial, like “Thandi M.”",
      artisanHint: "Your trading name, if you give one, is the name on your Profile.",
    },
    email: { step: "Email and password", email: "Email", password: "Password" },
    rules: {
      step: "Marketplace rules",
      accept: (version: number) => `I accept the Marketplace rules (version ${version}).`,
      read: "Read the rules",
    },
    send: "Send my Email code",
    continue: "Continue",
    change: "Change",
    haveAccount: "Already have an Account?",
  },
  consent:
    "I consent to ArtisanConnect using my personal data as the Marketplace rules describe, including storing it on Cloudflare's network outside South Africa.",
  confirm: {
    title: "Prove your Email",
    lead: (email: string) =>
      `We sent an email to ${email}. Enter the ${EMAIL_CODE.length}-digit code from it. It works once, for ${EMAIL_CODE.minutes} minutes.`,
    code: "Email code",
    submit: "Confirm",
    resend: "Send a new code",
    resent: "A new code is on its way. The old one no longer works.",
  },
  signIn: {
    title: "Sign in",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    forgot: "Forgot your password?",
    noAccount: "No Account yet?",
    enterCode: "Enter my code",
    rulesTitle: "The Marketplace rules have changed",
    rulesLead: "Accept the current version to sign in.",
    acceptAndSignIn: "Accept and sign in",
  },
  recover: {
    title: "Set a new password",
    lead: "We send a code to your Email if it holds an Account.",
    email: "Email",
    send: "Send a code",
    sent: (email: string) =>
      `If ${email} holds an Account, a code is on its way. It works once, for ${EMAIL_CODE.minutes} minutes.`,
    code: "Email code",
    password: "New password",
    submit: "Set the new password",
    done: "Your password is set. Every other session has been signed out.",
    signIn: "Sign in",
  },
  rules: {
    title: "Marketplace rules",
    version: (version: number, published: string) => `Version ${version}, published ${published}`,
    placeholder:
      "The full rules are being written. They will say how a Job, a Quote, a Hire, and the money work, what may be said, and how your personal data is used.",
  },
  notices: {
    title: "Notices",
    empty: "Nothing yet. We tell you here, and by email, when something needs you.",
    open: "Open",
  },
  jobs: {
    title: "Jobs",
    nextStep: "Next step",
    first: "Post your first Job",
    firstLead:
      "Describe the work, pick your suburb, and add photos. Verified Artisans near you send fixed-price Quotes.",
    post: "Post a Job",
    soon: "Posting a Job opens soon.",
  },
  verification: {
    title: "Verification",
    nextStep: "Next step",
    lead: "Before you can Quote, the Admin verifies who you are, your Payout account, and each trade you work in. A badge is a check the Admin accepted, not a promise about the work.",
    verifiedFor: (categories: string) => `You can Quote on ${categories} Jobs.`,
    notYet: "You are not verified for any Service Category yet.",
    gasWork: "gas work too",
    groups: {
      once: { title: "Once", lead: "Who you are, and where your Payouts go." },
      category: {
        title: "Per Service Category",
        lead: "Three photos of your own finished work in each trade, and any Credential it needs.",
      },
      optional: {
        title: "Optional",
        lead: "Extra badges on your Profile. Neither one changes what you may Quote on.",
      },
    },
    verified: "Verified",
    notVerified: "Not yet",
    states: {
      missing: "Not sent",
      waiting: "Waiting for the Admin",
      accepted: "Badge",
      expired: "Expired",
      rejected: "Rejected",
      removed: "Badge removed",
    },
    notNeeded: "Only needed with a foreign passport.",
    optionalCheck: "Optional",
    expires: (day: string) => `Expires ${day}`,
    expired: (day: string) => `Expired ${day}`,
    issued: (day: string) => `Issued ${day}`,
    reason: (reason: string) => `Reason: ${reason}`,
    replacementWaiting: "Your replacement is waiting for the Admin. This one counts until then.",
    replacementRejected: (reason: string) => `Your replacement was rejected: ${reason}`,
    submit: "Submit",
    submitAgain: "Submit again",
    replace: "Send a replacement",
    cancel: "Cancel",
    send: "Send to the Admin",
    sent: "Sent. The Admin checks it and we tell you the outcome.",
    fields: {
      documentType: "Kind of document",
      number: "Document number",
      saIdNumber: "South African ID number",
      country: "Country that issued it",
      chooseCountry: "Choose a country",
      expiresOn: "Expiry date",
      expiresOnOptional: "Expiry date (leave empty if it never expires)",
      issuedOn: "Issue date",
      registrationNumber: "Registration number",
      accountHolder: "Account holder, as the bank has it",
      bank: "Bank",
      branchCode: "Branch code",
      accountNumber: "Account number",
    },
    photosOnly: "Photos (JPEG, PNG, or WebP)",
    photosOrPdf: "Photos or PDFs, up to 10 MB each",
  },
  home: {
    waiting: "Waiting on you",
    verification: "Get verified to start quoting",
    open: "Open Verification",
    available: "Available for Jobs",
    availableOn: "You receive Job Matches.",
    availableOff: "No Job Matches. Your Profile stays visible.",
    regions: "Regions",
    noRegions: "You are offered Jobs only in the Regions you choose.",
    chooseRegions: "Choose Regions",
    editRegions: "Edit",
    regionsChosen: (count: number, max: number) => `${count} of ${max} chosen`,
    profile: "Profile",
    profileLead: "Your public page, with your work photos, badges, and Reviews.",
    openProfile: "Open",
  },
  regions: {
    title: "Regions",
    lead: "Choose one to three Regions you work in. You are offered Jobs only in these. Open a Region to see its suburbs.",
    suburbs: (count: number) => `${count} suburbs`,
    open: (region: string) => `Show the suburbs of ${region}`,
    close: (region: string) => `Hide the suburbs of ${region}`,
    chosen: (count: number, max: number) => `${count} of ${max} chosen`,
    save: "Save Regions",
    saved: "Your Regions are saved.",
    find: "Find your suburb",
    findLead: "See which Region a suburb is in.",
    findLabel: "Suburb",
    noMatch: "No official suburb matches that.",
  },
  account: {
    title: "Account",
    name: "Name",
    tradingName: "Trading name",
    none: "None",
    email: "Email",
    kind: "Kind",
    rules: "Marketplace rules",
    accepted: (version: number, when: string) => `Version ${version}, accepted ${when}`,
    support: "Contact support",
    supportLink: "Write to the Admin",
    signOut: "Sign out",
    names: {
      beingChecked: "Being checked",
      beingCheckedLead:
        "These names are being checked before anyone else sees them. Until then, others see the names shown above, if any.",
      notShown: "Nobody else sees your names until they pass the check.",
      refused: (reason: string) => `Your names were refused: ${reason}`,
      withdraw: "Withdraw",
      change: "Change names",
      save: "Save names",
      cancel: "Cancel",
      saved: "Your names are saved.",
      held: "Your names are being checked.",
    },
  },
  support: {
    title: "Contact support",
    lead: "Write to the Admin about anything on ArtisanConnect. The answer comes to your Email.",
    topic: "What it is about",
    message: "Your message",
    send: "Send to the Admin",
    sent: "Sent. The Admin's answer will come to your Email.",
    yours: "Your requests",
    none: "You have not written to the Admin yet.",
    sentAt: (when: string) => `Sent ${when}`,
    waiting: "Waiting",
    answered: (when: string) => `Answered by email, ${when}`,
  },
  admin: {
    signIn: {
      label: "Staff",
      title: "Admin sign-in",
      lead: "An Admin signs in with a code sent to their Email. There is no password.",
      email: "Email",
      send: "Send my sign-in code",
      sent: (email: string) =>
        `If ${email} is an Admin's Email, a code is on its way. It works once, for ${EMAIL_CODE.minutes} minutes.`,
      code: "Email code",
      submit: "Sign in",
      resend: "Send a new code",
      otherEmail: "Use another Email",
    },
    queues: {
      verification: "Verification",
      "pre-checks": "Pre-checks",
      signals: "Signals",
      reports: "Reports",
      disputes: "Disputes",
      chargebacks: "Chargebacks",
      support: "Support",
      "data-requests": "Data requests",
    },
    home: {
      title: "Queues",
      lead: "Every queue in one stream, oldest first.",
      all: "All",
      empty: "Nothing is waiting. Every queue is clear.",
      emptyQueue: "Nothing is waiting in this queue.",
      raised: (when: string) => `Raised ${when}`,
      open: "Open",
    },
    item: {
      queues: "Queues",
      open: "Open",
      decided: "Decided",
      decision: "Decision",
      choose: "Choose a decision",
      told: (who: string) => `Told: ${who}.`,
      final: "A recorded decision is final and cannot be reopened.",
      reason: "Reason",
      optional: (label: string) => `${label} (optional)`,
      record: "Record decision",
      recorded: (label: string) => `Decision recorded: ${label}`,
      by: (by: string, when: string) => `By ${by}, ${when}`,
      nothingAllowed: "No decision is allowed on this item now.",
      openRead: (label: string) => `Open ${label}`,
      logged: "(logged)",
      loggedNote: "Opening it is written to the audit log.",
      opened: (when: string) => `Opened at ${when}. Written to the audit log.`,
      timeline: "Timeline",
      pdf: "PDF, opens in a new tab",
      eachRow: "Decide each row on its own",
      rowsNow: "Each row as it stands now",
      noRows: "Nothing on this item is left to decide.",
    },
    admins: {
      title: "Admins",
      lead: "Every Admin holds every staff power, and every decision is written to the audit log. An Admin may remove another, but never the last.",
      invite: "Invite an Admin",
      inviteLead:
        "The invite goes to their Email. They sign in there with an Email code, from the Admin sign-in page.",
      email: "Email",
      send: "Send the invite",
      invited: (email: string) => `${email} is an Admin now. An invite is on its way to them.`,
      setUp: (when: string) => `Set up at deploy, ${when}`,
      invitedBy: (by: string, when: string) => `Invited by ${by}, ${when}`,
      you: "You",
      remove: "Remove",
      confirm: "Remove for good",
      cancel: "Keep",
      removeLead: (email: string) =>
        `${email} stops being an Admin and is signed out at once. This is written to the audit log.`,
      last: "The last Admin cannot be removed.",
    },
    audit: {
      title: "Audit log",
      lead: "Every Admin decision and every logged read: who, what, and when. Newest first. Nothing in it can be changed.",
      empty: "Nothing has been logged yet.",
      older: "Older",
    },
  },
  notBuilt: "This page is not built yet.",
  devMail: { title: "Local mailbox", empty: "No email sent since the app started." },
  notAPerson: "Complete the check above first.",
} as const;

/** A date as South Africans read it. */
export function formatDate(date: Date | string): string {
  return new Date(date).toLocaleString("en-ZA", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Africa/Johannesburg",
  });
}
