/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminSignInRouteImport } from './routes/admin/sign-in'
import { Route as ArtisansIndexRouteImport } from './routes/artisans.index'
import { Route as ArtisansArtisanIdRouteImport } from './routes/artisans.$artisanId'
import { Route as DevMailRouteImport } from './routes/dev/mail'
import { Route as FakeCheckoutCollectionIdRouteImport } from './routes/fake-checkout.$collectionId'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as WebhooksPaymentsRouteImport } from './routes/webhooks/payments'
import { Route as AdminFilesTokenRouteImport } from './routes/admin/files.$token'
import { Route as AdminItemsItemIdRouteImport } from './routes/admin/items.$itemId'
import { Route as AdminPayoutsIndexRouteImport } from './routes/admin/payouts.index'
import { Route as AdminPayoutsArtisanIdRouteImport } from './routes/admin/payouts.$artisanId'
import { Route as CompletionFilesCompletionIdFileIdRouteImport } from './routes/completion-files.$completionId.$fileId'
import { Route as DisputeFilesDisputeIdFileIdRouteImport } from './routes/dispute-files.$disputeId.$fileId'
import { Route as JobPhotosJobIdPhotoIdRouteImport } from './routes/job-photos.$jobId.$photoId'
import { Route as MessageFilesMessageIdFileIdRouteImport } from './routes/message-files.$messageId.$fileId'
import { Route as ProfilePhotosArtisanIdPhotoIdRouteImport } from './routes/profile-photos.$artisanId.$photoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignInRoute = AdminSignInRouteImport.update({
  id: '/admin/sign-in',
  path: '/admin/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansIndexRoute = ArtisansIndexRouteImport.update({
  id: '/artisans/',
  path: '/artisans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansArtisanIdRoute = ArtisansArtisanIdRouteImport.update({
  id: '/artisans/$artisanId',
  path: '/artisans/$artisanId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMailRoute = DevMailRouteImport.update({
  id: '/dev/mail',
  path: '/dev/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const FakeCheckoutCollectionIdRoute =
  FakeCheckoutCollectionIdRouteImport.update({
    id: '/fake-checkout/$collectionId',
    path: '/fake-checkout/$collectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksPaymentsRoute = WebhooksPaymentsRouteImport.update({
  id: '/webhooks/payments',
  path: '/webhooks/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFilesTokenRoute = AdminFilesTokenRouteImport.update({
  id: '/admin/files/$token',
  path: '/admin/files/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminItemsItemIdRoute = AdminItemsItemIdRouteImport.update({
  id: '/admin/items/$itemId',
  path: '/admin/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsIndexRoute = AdminPayoutsIndexRouteImport.update({
  id: '/admin/payouts/',
  path: '/admin/payouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsArtisanIdRoute = AdminPayoutsArtisanIdRouteImport.update({
  id: '/admin/payouts/$artisanId',
  path: '/admin/payouts/$artisanId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletionFilesCompletionIdFileIdRoute =
  CompletionFilesCompletionIdFileIdRouteImport.update({
    id: '/completion-files/$completionId/$fileId',
    path: '/completion-files/$completionId/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DisputeFilesDisputeIdFileIdRoute =
  DisputeFilesDisputeIdFileIdRouteImport.update({
    id: '/dispute-files/$disputeId/$fileId',
    path: '/dispute-files/$disputeId/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobPhotosJobIdPhotoIdRoute = JobPhotosJobIdPhotoIdRouteImport.update({
  id: '/job-photos/$jobId/$photoId',
  path: '/job-photos/$jobId/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageFilesMessageIdFileIdRoute =
  MessageFilesMessageIdFileIdRouteImport.update({
    id: '/message-files/$messageId/$fileId',
    path: '/message-files/$messageId/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfilePhotosArtisanIdPhotoIdRoute =
  ProfilePhotosArtisanIdPhotoIdRouteImport.update({
    id: '/profile-photos/$artisanId/$photoId',
    path: '/profile-photos/$artisanId/$photoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/home': typeof HomeRoute
  '/notices': typeof NoticesRoute
  '/payouts': typeof PayoutsRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/regions': typeof RegionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rules': typeof RulesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/artisans/$artisanId': typeof ArtisansArtisanIdRoute
  '/dev/mail': typeof DevMailRoute
  '/fake-checkout/$collectionId': typeof FakeCheckoutCollectionIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/webhooks/payments': typeof WebhooksPaymentsRoute
  '/admin/': typeof AdminIndexRoute
  '/artisans/': typeof ArtisansIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/files/$token': typeof AdminFilesTokenRoute
  '/admin/items/$itemId': typeof AdminItemsItemIdRoute
  '/admin/payouts/$artisanId': typeof AdminPayoutsArtisanIdRoute
  '/completion-files/$completionId/$fileId': typeof CompletionFilesCompletionIdFileIdRoute
  '/dispute-files/$disputeId/$fileId': typeof DisputeFilesDisputeIdFileIdRoute
  '/job-photos/$jobId/$photoId': typeof JobPhotosJobIdPhotoIdRoute
  '/message-files/$messageId/$fileId': typeof MessageFilesMessageIdFileIdRoute
  '/profile-photos/$artisanId/$photoId': typeof ProfilePhotosArtisanIdPhotoIdRoute
  '/admin/payouts/': typeof AdminPayoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/home': typeof HomeRoute
  '/notices': typeof NoticesRoute
  '/payouts': typeof PayoutsRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/regions': typeof RegionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rules': typeof RulesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/artisans/$artisanId': typeof ArtisansArtisanIdRoute
  '/dev/mail': typeof DevMailRoute
  '/fake-checkout/$collectionId': typeof FakeCheckoutCollectionIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/webhooks/payments': typeof WebhooksPaymentsRoute
  '/admin': typeof AdminIndexRoute
  '/artisans': typeof ArtisansIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/files/$token': typeof AdminFilesTokenRoute
  '/admin/items/$itemId': typeof AdminItemsItemIdRoute
  '/admin/payouts/$artisanId': typeof AdminPayoutsArtisanIdRoute
  '/completion-files/$completionId/$fileId': typeof CompletionFilesCompletionIdFileIdRoute
  '/dispute-files/$disputeId/$fileId': typeof DisputeFilesDisputeIdFileIdRoute
  '/job-photos/$jobId/$photoId': typeof JobPhotosJobIdPhotoIdRoute
  '/message-files/$messageId/$fileId': typeof MessageFilesMessageIdFileIdRoute
  '/profile-photos/$artisanId/$photoId': typeof ProfilePhotosArtisanIdPhotoIdRoute
  '/admin/payouts': typeof AdminPayoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/home': typeof HomeRoute
  '/notices': typeof NoticesRoute
  '/payouts': typeof PayoutsRoute
  '/profile': typeof ProfileRoute
  '/recover': typeof RecoverRoute
  '/regions': typeof RegionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rules': typeof RulesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/artisans/$artisanId': typeof ArtisansArtisanIdRoute
  '/dev/mail': typeof DevMailRoute
  '/fake-checkout/$collectionId': typeof FakeCheckoutCollectionIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/webhooks/payments': typeof WebhooksPaymentsRoute
  '/admin/': typeof AdminIndexRoute
  '/artisans/': typeof ArtisansIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/files/$token': typeof AdminFilesTokenRoute
  '/admin/items/$itemId': typeof AdminItemsItemIdRoute
  '/admin/payouts/$artisanId': typeof AdminPayoutsArtisanIdRoute
  '/completion-files/$completionId/$fileId': typeof CompletionFilesCompletionIdFileIdRoute
  '/dispute-files/$disputeId/$fileId': typeof DisputeFilesDisputeIdFileIdRoute
  '/job-photos/$jobId/$photoId': typeof JobPhotosJobIdPhotoIdRoute
  '/message-files/$messageId/$fileId': typeof MessageFilesMessageIdFileIdRoute
  '/profile-photos/$artisanId/$photoId': typeof ProfilePhotosArtisanIdPhotoIdRoute
  '/admin/payouts/': typeof AdminPayoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/confirm-email'
    | '/home'
    | '/notices'
    | '/payouts'
    | '/profile'
    | '/recover'
    | '/regions'
    | '/robots.txt'
    | '/rules'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/support'
    | '/verification'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/sign-in'
    | '/artisans/$artisanId'
    | '/dev/mail'
    | '/fake-checkout/$collectionId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/webhooks/payments'
    | '/admin/'
    | '/artisans/'
    | '/jobs/'
    | '/admin/files/$token'
    | '/admin/items/$itemId'
    | '/admin/payouts/$artisanId'
    | '/completion-files/$completionId/$fileId'
    | '/dispute-files/$disputeId/$fileId'
    | '/job-photos/$jobId/$photoId'
    | '/message-files/$messageId/$fileId'
    | '/profile-photos/$artisanId/$photoId'
    | '/admin/payouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/confirm-email'
    | '/home'
    | '/notices'
    | '/payouts'
    | '/profile'
    | '/recover'
    | '/regions'
    | '/robots.txt'
    | '/rules'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/support'
    | '/verification'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/sign-in'
    | '/artisans/$artisanId'
    | '/dev/mail'
    | '/fake-checkout/$collectionId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/webhooks/payments'
    | '/admin'
    | '/artisans'
    | '/jobs'
    | '/admin/files/$token'
    | '/admin/items/$itemId'
    | '/admin/payouts/$artisanId'
    | '/completion-files/$completionId/$fileId'
    | '/dispute-files/$disputeId/$fileId'
    | '/job-photos/$jobId/$photoId'
    | '/message-files/$messageId/$fileId'
    | '/profile-photos/$artisanId/$photoId'
    | '/admin/payouts'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/confirm-email'
    | '/home'
    | '/notices'
    | '/payouts'
    | '/profile'
    | '/recover'
    | '/regions'
    | '/robots.txt'
    | '/rules'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/support'
    | '/verification'
    | '/admin/admins'
    | '/admin/audit'
    | '/admin/sign-in'
    | '/artisans/$artisanId'
    | '/dev/mail'
    | '/fake-checkout/$collectionId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/webhooks/payments'
    | '/admin/'
    | '/artisans/'
    | '/jobs/'
    | '/admin/files/$token'
    | '/admin/items/$itemId'
    | '/admin/payouts/$artisanId'
    | '/completion-files/$completionId/$fileId'
    | '/dispute-files/$disputeId/$fileId'
    | '/job-photos/$jobId/$photoId'
    | '/message-files/$messageId/$fileId'
    | '/profile-photos/$artisanId/$photoId'
    | '/admin/payouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  HomeRoute: typeof HomeRoute
  NoticesRoute: typeof NoticesRoute
  PayoutsRoute: typeof PayoutsRoute
  ProfileRoute: typeof ProfileRoute
  RecoverRoute: typeof RecoverRoute
  RegionsRoute: typeof RegionsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RulesRoute: typeof RulesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  VerificationRoute: typeof VerificationRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminSignInRoute: typeof AdminSignInRoute
  ArtisansArtisanIdRoute: typeof ArtisansArtisanIdRoute
  DevMailRoute: typeof DevMailRoute
  FakeCheckoutCollectionIdRoute: typeof FakeCheckoutCollectionIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsNewRoute: typeof JobsNewRoute
  WebhooksPaymentsRoute: typeof WebhooksPaymentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArtisansIndexRoute: typeof ArtisansIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  AdminFilesTokenRoute: typeof AdminFilesTokenRoute
  AdminItemsItemIdRoute: typeof AdminItemsItemIdRoute
  AdminPayoutsArtisanIdRoute: typeof AdminPayoutsArtisanIdRoute
  CompletionFilesCompletionIdFileIdRoute: typeof CompletionFilesCompletionIdFileIdRoute
  DisputeFilesDisputeIdFileIdRoute: typeof DisputeFilesDisputeIdFileIdRoute
  JobPhotosJobIdPhotoIdRoute: typeof JobPhotosJobIdPhotoIdRoute
  MessageFilesMessageIdFileIdRoute: typeof MessageFilesMessageIdFileIdRoute
  ProfilePhotosArtisanIdPhotoIdRoute: typeof ProfilePhotosArtisanIdPhotoIdRoute
  AdminPayoutsIndexRoute: typeof AdminPayoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sign-in': {
      id: '/admin/sign-in'
      path: '/admin/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans/': {
      id: '/artisans/'
      path: '/artisans'
      fullPath: '/artisans/'
      preLoaderRoute: typeof ArtisansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans/$artisanId': {
      id: '/artisans/$artisanId'
      path: '/artisans/$artisanId'
      fullPath: '/artisans/$artisanId'
      preLoaderRoute: typeof ArtisansArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/mail': {
      id: '/dev/mail'
      path: '/dev/mail'
      fullPath: '/dev/mail'
      preLoaderRoute: typeof DevMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fake-checkout/$collectionId': {
      id: '/fake-checkout/$collectionId'
      path: '/fake-checkout/$collectionId'
      fullPath: '/fake-checkout/$collectionId'
      preLoaderRoute: typeof FakeCheckoutCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/payments': {
      id: '/webhooks/payments'
      path: '/webhooks/payments'
      fullPath: '/webhooks/payments'
      preLoaderRoute: typeof WebhooksPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/files/$token': {
      id: '/admin/files/$token'
      path: '/admin/files/$token'
      fullPath: '/admin/files/$token'
      preLoaderRoute: typeof AdminFilesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/items/$itemId': {
      id: '/admin/items/$itemId'
      path: '/admin/items/$itemId'
      fullPath: '/admin/items/$itemId'
      preLoaderRoute: typeof AdminItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts/': {
      id: '/admin/payouts/'
      path: '/admin/payouts'
      fullPath: '/admin/payouts/'
      preLoaderRoute: typeof AdminPayoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts/$artisanId': {
      id: '/admin/payouts/$artisanId'
      path: '/admin/payouts/$artisanId'
      fullPath: '/admin/payouts/$artisanId'
      preLoaderRoute: typeof AdminPayoutsArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completion-files/$completionId/$fileId': {
      id: '/completion-files/$completionId/$fileId'
      path: '/completion-files/$completionId/$fileId'
      fullPath: '/completion-files/$completionId/$fileId'
      preLoaderRoute: typeof CompletionFilesCompletionIdFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispute-files/$disputeId/$fileId': {
      id: '/dispute-files/$disputeId/$fileId'
      path: '/dispute-files/$disputeId/$fileId'
      fullPath: '/dispute-files/$disputeId/$fileId'
      preLoaderRoute: typeof DisputeFilesDisputeIdFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-photos/$jobId/$photoId': {
      id: '/job-photos/$jobId/$photoId'
      path: '/job-photos/$jobId/$photoId'
      fullPath: '/job-photos/$jobId/$photoId'
      preLoaderRoute: typeof JobPhotosJobIdPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message-files/$messageId/$fileId': {
      id: '/message-files/$messageId/$fileId'
      path: '/message-files/$messageId/$fileId'
      fullPath: '/message-files/$messageId/$fileId'
      preLoaderRoute: typeof MessageFilesMessageIdFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-photos/$artisanId/$photoId': {
      id: '/profile-photos/$artisanId/$photoId'
      path: '/profile-photos/$artisanId/$photoId'
      fullPath: '/profile-photos/$artisanId/$photoId'
      preLoaderRoute: typeof ProfilePhotosArtisanIdPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  HomeRoute: HomeRoute,
  NoticesRoute: NoticesRoute,
  PayoutsRoute: PayoutsRoute,
  ProfileRoute: ProfileRoute,
  RecoverRoute: RecoverRoute,
  RegionsRoute: RegionsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RulesRoute: RulesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  VerificationRoute: VerificationRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminSignInRoute: AdminSignInRoute,
  ArtisansArtisanIdRoute: ArtisansArtisanIdRoute,
  DevMailRoute: DevMailRoute,
  FakeCheckoutCollectionIdRoute: FakeCheckoutCollectionIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsNewRoute: JobsNewRoute,
  WebhooksPaymentsRoute: WebhooksPaymentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArtisansIndexRoute: ArtisansIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  AdminFilesTokenRoute: AdminFilesTokenRoute,
  AdminItemsItemIdRoute: AdminItemsItemIdRoute,
  AdminPayoutsArtisanIdRoute: AdminPayoutsArtisanIdRoute,
  CompletionFilesCompletionIdFileIdRoute:
    CompletionFilesCompletionIdFileIdRoute,
  DisputeFilesDisputeIdFileIdRoute: DisputeFilesDisputeIdFileIdRoute,
  JobPhotosJobIdPhotoIdRoute: JobPhotosJobIdPhotoIdRoute,
  MessageFilesMessageIdFileIdRoute: MessageFilesMessageIdFileIdRoute,
  ProfilePhotosArtisanIdPhotoIdRoute: ProfilePhotosArtisanIdPhotoIdRoute,
  AdminPayoutsIndexRoute: AdminPayoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
